
        <div class="select-container pfclear" style="width: 940px;">


          <div class="selectfirst active" style="min-width:260px;">
            <div class="productsearch">

              <span class="darkgray" style="float:left">First Cable Side</span>
              <div class="clearleft"></div>
              <span>
                <h3>$CABLE_LEFT$</h3>
              </span>

            </div>
            <div class="searched_image">
              <img src="$CABLE_LEFT_IMAGE$" style="height:50px;min-width:100px;">
</div>
          </div>



          <div class="connection-line" style="margin-top:44px;">
            <div class="arobox">
              <img src="images/connection-aro.png">
     </div>
          </div>

          <div class="selectsecond active" style="min-width:260px;">
            <div class="productsearch">

              <span class="darkgray" style="float:left">Second Cable Side</span>
              <div class="clearleft"></div>
              <span>
                <h3>$CABLE_RIGHT$</h3>
              </span>

            </div>
            <div class="searched_image">
              <img src="$CABLE_RIGHT_IMAGE$" style="min-width:100px;height: 50px">
</div>
          </div>
          <div class="view_option-wrap">
            <ul class="view_option">
              <li>
                <a href="#" id="list">
                  <span class="glyphicon glyphicon-th-list color_change1"> </span>Product List View
                </a>
              </li>
              <li>
                <a href="#" id="grid" >
                  <span class="glyphicon glyphicon-th color_change1"></span>Product Grid View
                </a>
              </li>
            </ul>
          </div>

        </div>
        $FILTER$
      
