
      
      
      <div class="final-result pfclear">

  <div class="final-image">
    <img src="$MODEL_IMAGE$" style="max-width:100px;max-height:100px" >
                                    
                                </div>

  <div class="final-brand">
    <h5>Device Brand</h5>
    <h3>$LEFT_BRAND$</h3>
  </div>

  <div class="final-model">
    <h5>Device Model</h5>
    <h3>$LEFT_MODEL$</h3>
  </div>

  <div class="view_option-wrap">
    <ul class="view_option">
      <li>
        <a href="#" id="list">
          <span class="glyphicon glyphicon-th-list color_change1"> </span>Product List View
        </a>
      </li>
      <li>
        <a href="#" id="grid" >
          <span class="glyphicon glyphicon-th color_change1"></span>Product Grid View
        </a>
      </li>
    </ul>
  </div>
        $FILTER$



      </div>
