<TD bgcolor="#F9F9F9">
  <table width="100%" border="0" cellspacing="0" cellpadding="6">
    <tr>
      <td width="100px" align="center" valign="top"  bgcolor="#F9F9F9" >
        <a href="family.aspx?&fid=$FAMILY_ID$&cid=$CATEGORY_ID$&pcr=$PARENT_CATEGORY_ID$&Path=$EA_PATH$">
          <img src="prodimages$ATTRIBUTE_ID_747$"  width="100" height="100" border="0" />
        </a>
      </td>
      <td  bgcolor="#F9F9F9" align="left">
        <strong>
          <a href="family.aspx?&fid=$FAMILY_ID$&cid=$CATEGORY_ID$&pcr=$PARENT_CATEGORY_ID$&Path=$EA_PATH$" style="text-decoration:none;">$FAMILY_NAME$</a>
        </strong>
        <p >
          $ATTRIBUTE_ID_90$
        </p>
        <p>
          $ATTRIBUTE_ID_91$
        </p>
        <p>
          $ATTRIBUTE_ID_377$
        </p>
        <p>
          $ATTRIBUTE_ID_379$
        </p>
        <p>
          $ATTRIBUTE_ID_4$
        </p>
        <table>
          <tr>
            <td>
              <strong>View</strong>:
            </td>
            <td>
              <a href="family.aspx?&fid=$FAMILY_ID$&cid=$CATEGORY_ID$&pcr=$PARENT_CATEGORY_ID$&Path=$EA_PATH$" class="tx_3">
                <img src="images/ico_details.gif" width="17" height="14" border="0" align="absmiddle" /></a>
            </td>
            <td>
              <a href="family.aspx?&fid=$FAMILY_ID$&cid=$CATEGORY_ID$&pcr=$PARENT_CATEGORY_ID$&Path=$EA_PATH$" class="tx_3">
                $PRODUCT_COUNT$ of $FAMILY_PRODUCT_COUNT$ Products
              </a>
            </td>
          </tr>
        </table>        
        <br/>
      </td>
    </tr>
    <tr>
      <td height="3">
      </td>
      <td>
      </td>
    </tr>
  </table>
</TD>