<table width="96%" border="0" cellpadding="0" cellspacing="0">

  <tr>
    <td>
      <table width="100%" border="0" cellspacing="0" cellpadding="5">
        <tr>
          <td align="left" class="tx_1">
            <a href="home.aspx" style="color:#0099FF" class="tx_3">Home</a><font style="font-family: Arial, Helvetica, sans-serif; font-weight:bolder; font-size: small; font-style: normal"> / </font>About Us
          </td>
        </tr>
        <tr>
          <td class="tx_3">
            <hr>
          </td>

        </tr>
      </table>
    </td>
  </tr>
  <tr>
    <td height="30" align="left" class="tx_7">ABOUT WES</td>
  </tr>
  <tr>
    <td align="center" valign="top" class="tx_1">
      <table width="558" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td height="30" background="images/17.gif">
            <table width="540" border="0" align="center" cellpadding="0" cellspacing="0">
              <tr>

                <td align="left" height="30" class="tx_6">INFORMATION</td>
                <td align="right">
                  <img src="images/ico_11.gif" width="14" height="17">
                  </td>
              </tr>
            </table>
          </td>
        </tr>
        <tr>
          <td class="back_table_center1">
            <table width="540" border="0" align="center" cellpadding="10" cellspacing="0" class="tx_1">
              <tr>
                <td align="left"  valign="top">                  
                  <p>
                    <span class="tx_3" style="text-decoration:none;">
                      <strong>WES Components is an importer/distributor of electronic Accessories and Components.</strong>
                    </span><br/>
We are dedicated to the supply of electronics accessories & spare parts to the technician, installer and engineer. Trade prices apply to registered customers only. </p>
                  <p>

                    <span class="tx_3" style="text-decoration:none;">
                      <strong>WES Components also supplies a large range of electronic accessories.</strong>
                    </span>
This is a vast expanding area, growing to accommodate the ever changing requests of our customers and maintaining high quality standards with a price winning structure. </p>
                  <p>
                    <span class="tx_3" style="text-decoration:none;">
                      <strong>
                        WES Components
                      </strong>
                    </span> has been a major supplier of spare parts for the electronic service industry for over 20 years. Our vast range includes <a href="http://www.cellink.com.au" target="blank"><span class="tx_3">
                        <u>cellular</u></span></a> and communications (CB, UHF etc.) accessories; batteries for <a href="http://www.cellink.com.au" target="blank"><span class="tx_3">
                      <u>mobile</u></span></a>, cordless, drills, video, etc., eliminators,<a href="http://www.fonedecor.com" target="blank"><span class="tx_3"><u>phone housings</u></span></a>, cases, holsters, lenses, hands-free kits, housings, key pads, desktop chargers, twin chargers, saver chargers, replacement antennae, car antennae, bases, power packs, transformers, 24V to 12V converters, mounting brackets, cables, tools, test equipment, service aids, soldering,<a href="http://www.gamemaster.com.au" target="blank"><span class="tx_3"><u>Game console accessories</u></span></a>, computer leads and parts, audio/video/communication plugs, sockets and adaptors, leads, cable, AC components and accessories, automotive audio parts and accessories for installers, a large range of home theatre improvement accessories, ICs, transistors, electronic components, switches, speakers, spare parts for TV, VCR, CD, DVD, audio and much more!
                  </p>
                  <p>
                    We pride our selves on our price and availability, so all items should be in stock. Also, this is an ever expanding range. If you require something not listed, please contact us. We could get it in, or it may have been added already.
                  </p>
                  <p>
                    Most of the items we have available are attractively packaged in hanger/blister packs for ease of display.
                  </p>
                  <p>
                    <span class="tx_3" style="text-decoration:none;">
                      <strong>WES Components</strong>
                    </span>offers a fast, efficient spare parts and accessories supply service designed to save the customer time and money. We have many open telephone lines to take your enquiries. Also Fax and Modem lines. Payment can be made by either credit card, cheque with order, or payment by bank transfer. We recommend credit card, by doing so you may be eligible for your fly-buy or frequent flyer points. We accept Bankcard, Mastercard, Visa, Diners Club and American Express.
                  </p>
                </td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
      <br>
        <br>
          <br>

            <br>
              <br>
                <br>
    </td>
  </tr>
</table>