<div class="itemcategory">
  <a href="$TBT_REMOVEURL$&amp;path=$TBT_REMOVEEAPATH$" class="remove">
    <!--<img src="images/close11.png" alt="remove" name="change" width="11" height="11"   />-->
    <!--<img class="remove" width="10" height="8"  name="change" alt=""/>-->
  </a>
  
  <span class="removertxt">
    <strong style="padding-left: 5px;">$TBW_ITEM_TYPE$</strong>
    <br/>
      <a href="$TBT_URL$&amp;path=$TBT_EAPATH$">$TBW_ITEM_NAME$</a>
    </span>
</div>