
<table align="center" width="100%" border="0" cellpadding="0" cellspacing="0" class="border_1">
  <tr>
    <td valign="bottom">
      <table width="100%" border="0" cellpadding="0" cellspacing="0" class="tx_1">
        <tr height="35">
          <td>
            <table width="100%" border="0" cellpadding="0" cellspacing="0" class="tx_1">
              <tr>
              <TD height="39" vAlign="top" width="11">
                <IMG alt="" src="Images/Fr_Cr_5.png" width="11" height="39">
              </TD>
              <TD style="BACKGROUND-IMAGE: url(Images/Fr_center_1.png); BACKGROUND-REPEAT: repeat-x" class="txt_14" height="39" width="550" align="left">
                <IMG hspace="10" alt="" src="Images/downarrow_G.png" width="24" height="12"> $TBW_CATEGORY_NAME$ 
              </TD>
              <TD height="39" vAlign="top" width="10">
                <IMG alt="" src="Images/Fr_Cr_6.png" width="10" height="39" /> 
            </TD>
              </tr>
            </table>
          </td>         
        </tr>       
      </table>
    </td>
  </tr>
  <tr style="display:$TBT_DISPLAY_LINK$;">
    <td>
      <table width="100%" bgColor="#f2f2f2" border="0" cellSpacing="0" cellPadding="0">
        <tr>
          <TD align="left" height="25"  width="30">
          </TD>
          <TD align="left" height="25"  width="730">
             
              <a href="$TBT_EBOOK_LINK$" target="_blank" style="color:Blue;float:left;display:$TBT_DISPLAY_EBOOK_LINK$;">View eBook &nbsp;&nbsp;&nbsp; - &nbsp;&nbsp;&nbsp;</a>
              <!--<a href="attachments$PDF$" target="_blank" style="color:Blue;display:$TBT_DISPLAY_PDF_LINK$;">View PDF</a>-->
              <a href="$PDF$" target="_blank" style="color:Blue;display:$TBT_DISPLAY_PDF_LINK$;">View PDF</a>
           
          </TD>
        </tr>
      </table>
    </td>
  </tr>
  <tr>
    <td align="center">
      <iframe src="$TBT_ADV_URL_LINK$" border="0" frameborder="0" width="780" height="1000px" ></iframe>
    </td>
  </tr> 
</table>
