<table width="96%" border="0" cellpadding="0" cellspacing="0">
  <tr>
    <td>
      <table width="100%" border="0" cellspacing="0" cellpadding="5">
        <tr>
          <td class="tx_1" align="left">
            <a href="home.aspx" style="color:#0099FF" class="tx_3">Home</a><font style="font-family: Arial, Helvetica, sans-serif; font-weight:bolder; font-size: small; font-style: normal"> / </font>Returns
          </td>
        </tr>
        <tr>
          <td class="tx_3">
            <hr/>
          </td>
        </tr>
      </table>
    </td>
  </tr>
  <tr>
    <td height="30" class="tx_7" align="left">
      RETURNS<br/>
    </td>
  </tr>
  <tr>
    <td class="tx_1" align="left">
      <p>
        In order to ensure fast, efficient processing of all returns, it is important that you read our return policy here. Once you have finished, please continue filling out this form.<br>
          <br/>
              For defective products, first contact the warranty service provider listed in the Warranty section of the product description. If, after contacting the warranty service provider, the product has not been repaired to your satisfaction, we will work with you to obtain an appropriate resolution.</p>
      <p>For all other returns: If approved, we or the shipping vendor will issue you a Return Merchandise Authorization Number (RMA#). No unauthorized returns will be accepted. All returns must be in &quot;as-new&quot; condition, and in the original packaging, complete with: manuals, registration cards, and accessories. We will refund your credit card charges once the product has been received, inspected and tested. Please refer to our Return Policy help section for more information.</p>
    </td>
  </tr>
  <tr>
    <td align="center" valign="top">&nbsp;</td>
  </tr>
</table>

  


















