<table width="180" border="0" cellpadding="0" cellspacing="0">  
  <tr>
    <td width="180" height="30" valign="top">
      <div class="title6" style="font-weight:normal;text-align:left;">Cable Finder</div>
    </td>
  </tr>
  <tr>
    <td height="92" valign="top">
      <div  style="color: black; position: relative;">
        <img src="/images/loading.gif" id="imgCable2" style="display:none;top: 55px; left: 124px; position: absolute;"/>
      <table width="100%" border="0" cellpadding="0" cellspacing="0" class="search_bdr">       
        <tr>
          <td width="10" height="15" colspan=""></td>
          <td width="158"></td>
          <td width="12"></td>
        </tr>
        $TBWDataList:{
        $it.TBWDataListItem$}$    
        <tr>
        <td width="10" height="0" colspan=""></td>
        <td width="158">
          
          <a onclick="GetCableFinderURL();" style="width:100px;cursor:pointer;" class="toplinkatest"   >Find My Cable </a>
          <!--class="moreinfo button smallsiz btnblue"-->
        </td>
        <td width="12"></td>
      </tr>
      </table>
      </div>
    </td>
    
  </tr>
  
  <tr>
    <td height="10" valign="top">
    </td>
  </tr>
</table>