<tr><td>
 
</td>
<td  valign="middle" align="center">
	<table><tr><td class="dropdown_bdr">
 <select id="$TBW_SELECTED_ID$" style="overflow:auto;border-top-style:none;border-right-style:none;border-bottom-style:none;border-left-style:none;font-family:Arial, Helvetica, sans-serif;font-size:12px;color:#333333;width:142px;" onchange="GetSelectedCable('$TBW_SELECTED_ID$')" name="lst1">$TBWDataList:{$it.TBWDataListItem$}$</select></td></tr></table>  
</td>
  <td>&nbsp;</td>
</tr>
<tr>
  <td colspan="3" >&nbsp;   
</td>
</tr>