<table>
  <tr>
    <td height="3px">&nbsp;</td>
  </tr>
</table>
<table width="180" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td class="back_5">
      <table width="160" border="0" align="center" cellpadding="0" cellspacing="0">
        <tr>
          <td height="30" class="tx_6" align="left">&nbsp;ANNOUNCEMENTS</td>
          <td>
            <img src="images/ico_11.gif" width="14" height="17">
          </td>
        </tr>
      </table>
    </td>
  </tr>
  <tr>
    <td>
      <table width="180" border="0" cellpadding="5" cellspacing="0" class="tx_1">
        <tr>
          <td align="left" class="back_tb_cost">
            <p>
              <strong>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</strong>
            </p>
            <p>Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer.</p>
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>