<td align="left">
  <!--<a href="attachments/$PDF$" target="_blank">-->
  <a href="$PDF$" target="_blank">
    <img src="images/121.png" />
  </a> 
  <!--<a href="attachments/$PDF$" target="_blank" style="color:Blue">$PDF$</a>-->
  <a href="$PDF$" target="_blank" style="color:Blue">$PDF$</a>
</td>
<td align="center">$PDFFILEDESCRIPTION$</td>
<td align="center">$PDF_DATE$</td>
<td align="center">$PDF_SIZE$</td>
