<table width="100%" border="0" cellpadding="0" cellspacing="0">
  <tr>
    <td  align="center">
      <table  border="0">
         <tr>
          <td valign="top"  align="center" colspan="2" align="left">
            <table width="580" class="border_7" >
              <tr>
                <td align="center" class="tx_7" bgcolor="#0077cc" style="color:white;font-size:10px;">
                  File Name
                </td>
                <td align="center" class="tx_7" bgcolor="#0077cc" style="color:white;font-size:10px;">
                  File Description
                </td>
                <td align="center" class="tx_7" bgcolor="#0077cc" style="color:white;font-size:10px;">Modified</td>
                <td align="center" class="tx_7" bgcolor="#0077cc" style="color:white;font-size:10px;">Size</td>
              </tr>
              $TBWDataList:{
              $it.TBWDataListItem$}$
            </table>
          </td>
        </tr>
      </table>
    </td>
  </tr>
  <tr>
    <td >
    <br/>
    <br/>
    </td>
  </tr>
</table>



