<html>

<head>
<meta http-equiv="Content-Language" content="en-us">
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<title>Order Ready For PickUp</title>
<style>
<!--
div.Section1
	{page:Section1;}
.style1 {
				font-family: Arial, Helvetica, sans-serif;
				font-size: x-small;
				border-width: 1px;
				background-color: #0091C7;
}
.style2 {
				font-family: Arial;
				font-size: 9pt;
				color: #FFFFFF;
}
.style3 {
				border-width: 1px;
				background-color: #0089BC;
}
.style4 {
				border-width: 1px;
}
.style6 {
				border-width: 1px;
				background-color: #FFFFFF;
}
.style7 {
				border-width: 1px;
				background-color: #0092C8;
}
.style8 {
				font-family: Arial, Helvetica, sans-serif;
				font-size: x-small;
				border-width: 1px;
				background-color: #0092C8;
}
.style9 {
				font-family: Arial;
				font-size: 9pt;
}
.style10 {
				border-width: 1px;
				background-color: #E0E0E0;
}
-->
</style>
</head>
<body>
<div>

<table style="padding: 0px; margin: 0px; width: 530px; border: 1px solid #333333; border-collapse: collapse">
	<tr>
		<td style="border: 1px solid #333333; padding: 0px; margin: 0px; border-collapse: collapse">
		<a target="_blank" href="http://www.wes.com.au/">
		<img alt="wes" img border="0" src="http://www.wescomponents.com/wes_einvoice/wes_email_header_pickup.gif" style="border-width: 0px; border-style: none" /></a></td>
	</tr>
	<tr>
		<td style="border: 1px solid #333333; padding: 0px 0px 0px 20px; margin: 0px; border-collapse: collapse">
		<br />
		<p style="font-family: arial, Helvetica, sans-serif; font-size: 15pt; font-weight: bold;">Order Ready for Pick Up!</p>
		<p style="font-family: arial, Helvetica, sans-serif; font-size: 10pt; margin-top: 30px;">
		Dear Customer,</p>
		<p style="font-family: arial, Helvetica, sans-serif; font-size: 10pt">Your order is now completed and 
		is ready for pick up from our store.</p>
	
		<table border="1" width="450" bordercolor="#000000" style="border-collapse: collapse" cellpadding="2">
			<tr>
				<td width="450" bordercolor="#000000" bgcolor="#0092C8" height="25" colspan="3">
				<p align="left" style="margin-left: 3px">
				<font style="font-size: 10pt; font-family: arial, Helvetica, sans-serif; padding-left: 3px; color: #FFFFFF;">Invoice Information</font></td>
			</tr>
			<tr>
				<td width="150" bordercolor="#000000" bgcolor="#F3F3F3" style="height: 25px">
				<p align="left" style="margin-left: 3px">
				<font style="font-size: 10pt; font-family: arial, Helvetica, sans-serif; padding-left: 3px;">Date</font></td>
				<td width="150" bordercolor="#000000" bgcolor="#F3F3F3" style="height: 25px">
				<p align="left" style="margin-left: 3px">
				<font style="font-size: 10pt; font-family: arial, Helvetica, sans-serif; padding-left: 3px;">Your Order No</font></td>
				<td width="150" bordercolor="#000000" bgcolor="#F3F3F3" style="height: 25px">
				<p align="left" style="margin-left: 3px">
				<font style="font-size: 10pt; font-family: arial, Helvetica, sans-serif; padding-left: 3px;">Invoice No</font></td>
			</tr>
			<tr>
				<td bordercolor="#000000" height="25">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" color="#000000" style="font-size: 10pt; font-family: arial, Helvetica, sans-serif; padding-left: 3px;">$Invoicedate$</font></td>
				<td bordercolor="#000000" height="25">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" color="#000000" style="font-size: 10pt; font-family: arial, Helvetica, sans-serif; padding-left: 3px;">$CustOrderNo$</font></td>
				<td bordercolor="#000000" height="25">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" color="#000000" style="font-size: 10pt; font-family: arial, Helvetica, sans-serif; padding-left: 3px;">$INVOICENO$</font></td>
			</tr>
		</table>

	
		<p style="font-family: arial, Helvetica, sans-serif; font-size: 10pt; margin-top: 30px; margin-bottom: 10px;">
		<strong>Important<br />
		</strong>When picking up goods from our store please bring the following 
		with you:</p>
		<ul>
			<li>
			<p style="font-family: arial, Helvetica, sans-serif; font-size: 10pt; margin-bottom: 15px;">
			Printed copy of the Invoice.
			(PDF Invoice Attached) </p>
			</li>
			<li>
			<p style="font-family: arial, Helvetica, sans-serif; font-size: 10pt">Identification such as Driver&#39;s License / Proof of Age Card / Passport</p>
			</li>
		</ul>
		<p style="font-family: arial, Helvetica, sans-serif; font-size: 10pt; margin-top: 30px;">
		<a style="color: #000000; text-decoration: none;" href="https://goo.gl/maps/rVvQC7LeRRt">
		<strong>Store Pick Up Location</strong>
			<br />
		
			WES Australasia<br />
			84-90 Parramatta Road,<br />
			Summer Hill, NSW 2130<br />
		<br />
		Basement Parking Available.
		<br>
		<br>
		-- <strong style="color: #0000FF">View Directions --</strong></a> </p>
		<p style="font-family: arial, Helvetica, sans-serif; font-size: 10pt; margin-top: 30px;">
		<strong>Business Hours<br />
		</strong>8.30AM - 5PM Monday to Friday<br />
		9.00AM - 4PM Saturday<br />
		Excluding Public Holidays</p>
		<p style="font-family: arial, Helvetica, sans-serif; font-size: 10pt; margin-top: 35px;">
		Best Regards<br />
		WES Team<br />
		<br />
		Phone: (02) 9797 9866<br />
		Email: <a href="mailto:sales@wes.com.au">sales@wes.com.au</a><br />
		Web: <a href="http://www.wes.com.au/">http://www.wes.com.au/</a><br />
		&nbsp;</p>
		<p style="font-family: arial, Helvetica, sans-serif; font-size: 10pt; margin-top: 30px;">
		&nbsp;</p>
		<p></p></td>
	</tr>
</table>

</div>


</body></html>