<html>

<head>
<meta http-equiv="Content-Language" content="en-us">
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<title>Your Items in Cart - WES Australasia</title>
<style>
<!--
div.Section1
	{page:Section1;}
.style1 {
				font-family: Arial, Helvetica, sans-serif;
				font-size: x-small;
				border-width: 1px;
				background-color: #0091C7;
}
.style2 {
				font-family: Arial;
				font-size: 9pt;
				color: #FFFFFF;
}
.style3 {
				border-width: 1px;
				background-color: #0089BC;
}
.style4 {
				border-width: 1px;
}
.style6 {
				border-width: 1px;
				background-color: #FFFFFF;
}
.style7 {
				border-width: 1px;
				background-color: #0092C8;
}
.style8 {
				font-family: Arial, Helvetica, sans-serif;
				font-size: x-small;
				border-width: 1px;
				background-color: #0092C8;
}
.style9 {
				font-family: Arial;
				font-size: 9pt;
}
.style10 {
				border-width: 1px;
				background-color: #E0E0E0;
}
-->
</style>
</head>

<body rightmargin="0">
		<table cellpadding="0" width="502" height="520" style="border-collapse: collapse" border="1" bordercolor="#000000" cellspacing="0">
	<tr>
		<td valign="top" height="64" width="500">
		<img alt="WES" src="http://wes.com.au/images/wes_open_order.gif" width="500" height="71"/></td>
	</tr>
	<tr>
		<td valign="top" height="449" width="525">
		<table cellpadding="0" cellspacing="0" border="0" width="490" height="439">
			<!-- MSCellFormattingTableID="2" -->
			<tr>
				<td height="439" width="490">
				<!-- MSCellFormattingType="content" -->
				<table border="0" width="468" height="350" cellpadding="10" cellspacing="0">
					<tr>
						<td valign="top" width="448">
											<p align="left" style="margin-left: 3px">
											<i><b><font face="Arial" size="4">
											<span lang="en-au">Your Cart is Open with Products
											 - </span>WES Australasia</font></b></i><font size="2" face="Arial"><br>
											<br />
											<span lang="en-au">Dear $CONTACT$,</span><br/>
                                            	<br/>
                                           <span lang="en-au"> Thanks for Visiting WES Australasia!</span>
											<br/>
											
											<span lang="en-au">Your shopping cart is still open! it has been reserved and waiting your return!<br/>
                                            </span>
											<br/>
											<b>Email:</b> 
											<a href="mailto:sales@wes.net.au" style="color:#0000FF;">sales@wes.net.au</a><br/>
											<b>Phone:</b> 02-9797-9866<br/>
											<b>Fax:</b> 02-9716-6015</font></p>
	
										<span lang="en-au">Your cart has the following products in it: </span>
                                       <br /><br />
		<table border="1" width="449" id="table10" bordercolor="#000000" style="border-collapse: collapse" cellpadding="2">
			<tr>
				<td width="450" bordercolor="#000000" height="24" colspan="2"  style="font-family: Arial, Helvetica, sans-serif;font-size: x-small;border-width: 1px;background-color: #0091C7;" class="style1">
				<font color="#FFFFFF"><span lang="en-au"  style="font-family: Arial;font-size: 9pt;color: #FFFFFF;" >Order Contents</span></font></td>
			</tr>
					<tr>
				<td bordercolor="#000000" height="24" style="width: 294px;border-width: 1px;background-color: #E0E0E0;" class="style10">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt"><span lang="en-au">
				Order Code</span></font></td>
				<td width="150" bordercolor="#000000" height="20" style="width: 300px;border-width: 1px;background-color: #E0E0E0;" class="style10">
				<p align="left" style="margin-left: 3px"  style="font-family: Arial;font-size: 9pt;" class="style9">
				<span lang="en-au">Qty</span></td>
				</tr>
		$TBWDataList:{
        $it.TBWDataListItem$}$

		</table>
        <p style="height: 10px;">
        Complete your purchase by clicking on the link below:
        </p>
        <a href="$TBT_CHKOUT_URL$" style="color:#0000FF;">View and Complete Order</a>  
  											<p align="left" style="margin-left: 3px">
											<font size="2" face="Arial">Best Regards,<br/>
											WES Team
                                                     <br />
                                              <a href="http://wes.com.au" style="text-decoration:none;color:#0000FF;">www.wes.com.au</a>
                                            </font>
                                                                            
                                            </p>
										</td>
					</tr>
					</table>
				</td>
			</tr>
		</table>
		</td>
	</tr>
	</table>
		</body>

</html>