<html>

<head>
<meta http-equiv="Content-Language" content="en-us">
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<title>Wes New Customer</title>
<style>
<!--
div.Section1
	{page:Section1;}
.style1 {
				font-family: Arial, Helvetica, sans-serif;
				font-size: x-small;
				border-width: 1px;
				background-color: #0091C7;
}
.style2 {
				font-family: Arial;
				font-size: 9pt;
				color: #FFFFFF;
}
.style3 {
				border-width: 1px;
				background-color: #0089BC;
}
.style4 {
				border-width: 1px;
}
.style6 {
				border-width: 1px;
				background-color: #FFFFFF;
}
.style7 {
				border-width: 1px;
				background-color: #0092C8;
}
.style8 {
				font-family: Arial, Helvetica, sans-serif;
				font-size: x-small;
				border-width: 1px;
				background-color: #0092C8;
}
.style9 {
				font-family: Arial;
				font-size: 9pt;
}
.style10 {
				border-width: 1px;
				background-color: #E0E0E0;
}
-->
</style>
</head>

<body rightmargin="0">
		<table cellpadding="0" width="527" height="520" style="border-collapse: collapse" border="1" bordercolor="#000000" cellspacing="0">
	<tr>
		<td valign="top" height="64" width="525">
		<img alt="WES" src="http://wes.com.au/images/wes_orderconfirmation.gif" width="525" height="71"></td>
	</tr>
	<tr>
		<td valign="top" height="449" width="525">
		<table cellpadding="0" cellspacing="0" border="0" width="490" height="439">
			<!-- MSCellFormattingTableID="2" -->
			<tr>
				<td height="439" width="490">
				<!-- MSCellFormattingType="content" -->
				<table border="0" width="468" height="400" cellpadding="10" cellspacing="0">
					<tr>
						<td valign="top" width="448">
											<p align="left" style="margin-left: 3px">
											<i><b><font face="Arial" size="4">
											<span lang="en-au">Online Submitted 
											Order - </span>WES Australasia</font></b></i><font size="2" face="Arial"><br>
											<br>
											<span lang="en-au">Thanks for your 
											order. Your Order has now been 
											submitted to us for processing. 
											Please see below for your submitted 
											order details. Please note this is 
											not the final invoice and only a 
											confirmation we have received your 
											order.<br>
											<br>
											</span>If there <span lang="en-au">
											is</span> 
											any incorrect details or concerns 
											please contact us<span lang="en-au"> 
											ASAP on</span>:<br>
											<br>
											<b>Email:</b> 
											<a href="mailto:sales@wes.net.au">sales@wes.net.au</a><br>
											<b>Phone:</b> 02-9797-9866<br>
											<b>Fax:</b> 02-9716-6015</font></p>
		<table border="1" width="449" id="table7" bordercolor="#000000" style="border-collapse: collapse" cellpadding="2">
			<tr>
				<td bordercolor="#000000" height="20" colspan="3" style="border-width: 1px;background-color: #0092C8;" class="style7">
				<font face="Arial" size="2" color="#FFFFFF">Order Information</font></td>
			</tr>
			<tr>
				<td width="150" bordercolor="#000000" style="height: 20px;border-width: 1px;background-color: #E0E0E0;" class="style10">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt">Date</font></td>
				<td width="150" bordercolor="#000000" style="height: 20px;border-width: 1px;background-color: #E0E0E0;" class="style10">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt"><span lang="en-au">
				Customer&nbsp; Order No</span></font></td>
				<td width="150" bordercolor="#000000" style="height: 20px;border-width: 1px;background-color: #E0E0E0;" class="style10">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt"><span lang="en-au">
				Shipping Method</span></font></td>
			</tr>
			<tr>
				<td bordercolor="#000000" height="20" class="style4">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt">$OrderDate$</font></td>
				<td bordercolor="#000000" height="20" class="style4">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt">$CustOrderNo$</font></td>
				<td bordercolor="#000000" height="20" class="style4" style="width: 151px">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt"><span lang="en-au">
				$ShippingMethod$</span></font></td>
			</tr>
		</table>
											<br>
		<table border="1" width="449" id="table8" bordercolor="#000000" style="border-collapse: collapse" cellpadding="2">
			<tr>
				<td width="450" bordercolor="#000000" height="20" colspan="2" style="font-family: Arial, Helvetica, sans-serif;font-size: x-small;border-width: 1px;background-color: #0092C8;" class="style8">
				<font color="#FFFFFF"><span lang="en-au"  style="font-family: Arial;font-size: 9pt;color: #FFFFFF;">User </span style="font-family: Arial;font-size: 9pt;color: #FFFFFF;">Information</font></td>
			</tr>
			<tr>
				<td bordercolor="#000000" height="20" style="width: 294px;border-width: 1px;background-color: #E0E0E0;" class="style10">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt"><span lang="en-au">
				Created By User</span></font></td>
				<td bordercolor="#000000" height="20" style="width: 294px;border-width: 1px;background-color: #E0E0E0;" class="style10">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt"><span lang="en-au">&nbsp;Submitted 
				By User</span></font></td>
				</tr>
			<tr>
				<td bordercolor="#000000" height="20" style="width: 294px" class="style4">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt">$CreatedBy$
				</font></td>
				<td bordercolor="#000000" height="20" class="style4">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt">$SubmittedBy$ 
				</font></td>
				</tr>
		</table>
											<br>
		<table border="1" width="449" id="table9" bordercolor="#000000" style="border-collapse: collapse" cellpadding="2">
			<tr>
		
				<td bordercolor="#000000" style="width: 294px; height: 20px;border-width: 1px;background-color: #0089BC;" class="style3">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" color="#FFFFFF" style="font-size: 9pt">
				<span lang="en-au">&nbsp;Billing Details</span></font></td>
				<td bordercolor="#000000" style="width: 294px; height: 20px;border-width: 1px;background-color: #0089BC;" class="style3">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" color="#FFFFFF" style="font-size: 9pt">
				<span lang="en-au">&nbsp;Shipping Details</span></font></td>
				</tr>
			<tr>
				<td bordercolor="#000000" height="20" style="width: 294px" class="style6">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt">$BillingAddress$ </font></td>
				<td bordercolor="#000000" height="20" style="width: 302px" class="style6">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt">$ShippingAddress$</font></td>
				</tr>
		</table>
											<br>
											$if(TBT_shippingnotes)$
		  <table border="1" width="449" id="table10" bordercolor="#000000" style="border-collapse: collapse" cellpadding="2">
             <tr>
				<td  bordercolor="#000000" height="20" colspan="2" style="font-family: Arial, Helvetica, sans-serif;font-size: x-small;border-width: 1px;background-color: #0091C7;" class="style1">
				<span lang="en-au" style="font-family: Arial;font-size: 9pt;color: #FFFFFF;" class="style2">Order Comments</span></td>
			</tr>

			<tr>
				<td bordercolor="#000000" height="20"  style="border-width: 1px;background-color: #FFFFFF;" class="style6" colspan="2">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt">$shippingnotes$</font></td>
            </tr> 
  </table>
		<br>									
		$endif$
		<table border="1" width="449" id="table10" bordercolor="#000000" style="border-collapse: collapse" cellpadding="2">
			<tr>
				<td width="450" bordercolor="#000000" height="20" colspan="2"  style="font-family: Arial, Helvetica, sans-serif;font-size: x-small;border-width: 1px;background-color: #0091C7;" class="style1">
				<font color="#FFFFFF"><span lang="en-au"  style="font-family: Arial;font-size: 9pt;color: #FFFFFF;" >Order Contents</span></font></td>
			</tr>
			<tr>
				<td bordercolor="#000000" height="20" style="width: 294px;border-width: 1px;background-color: #E0E0E0;" class="style10">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt"><span lang="en-au">
				Order Code</span></font></td>
				<td width="150" bordercolor="#000000" height="20" style="width: 300px;border-width: 1px;background-color: #E0E0E0;" class="style10">
				<p align="left" style="margin-left: 3px" class="style9">
				<span lang="en-au">QTY</span></td>
				</tr>
			$TBWDataList:{
        $it.TBWDataListItem$}$
		</table>
											<p align="left" style="margin-left: 3px">
											<font size="2" face="Arial">Best Regards,<br>
											WES Team</font></p>
										</td>
					</tr>
					</table>
				</td>
			</tr>
		</table>
		</td>
	</tr>
	</table>
		</body>

</html>