<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Wes New Customer</title>
</head>

<body>


<head>
<style>
<!--
div.Section1
	{page:Section1;}
.style1 {
				font-family: Arial, Helvetica, sans-serif;
				font-size: x-small;
				border-width: 1px;
				background-color: #0091C7;
}
.style2 {
				font-family: Arial;
				font-size: 9pt;
				color: #FFFFFF;
}
.style3 {
				border-width: 1px;
				background-color: #0089BC;
}
.style4 {
				border-width: 1px;
}
.style6 {
				border-width: 1px;
				background-color: #FFFFFF;
}
.style7 {
				border-width: 1px;
				background-color: #0092C8;
}
.style8 {
				font-family: Arial, Helvetica, sans-serif;
				font-size: x-small;
				border-width: 1px;
				background-color: #0092C8;
}
.style9 {
				font-family: Arial;
				font-size: 9pt;
}
.style10 {
				border-width: 1px;
				background-color: #E0E0E0;
}
p { font-family:Arial, Helvetica, sans-serif;}
-->
</style>
</head>

<body rightmargin="0">
		<table cellpadding="0" width="527" height="520" style="border-collapse: collapse" border="1" bordercolor="#000000" cellspacing="0">
	<tr>
		<td valign="top" height="64" width="525">
		<img alt="WES" src="http://wes.com.au/images/wes_orderconfirmation.gif" width="525" height="71"></td>
	</tr>
	<tr>
		<td valign="top" height="449" width="525">
		<table cellpadding="0" cellspacing="0" border="0" width="490" height="439">
			<!-- MSCellFormattingTableID="2" -->
			<tr>
				<td height="439" width="490">
				<!-- MSCellFormattingType="content" -->
				<table border="0" width="468" height="400" cellpadding="10" cellspacing="0">
					<tr>
						<td valign="top" width="448">
											<p align="left" style="margin-left: 3px">
											<b><font face="Arial" size="4">
											<span lang="en-au">WES Order Confirmation</span>
										</font></b>
											<p size="2" face="Arial" style="font-size:15px; font-weight:bold; margin-top:16px;color:#DC133C;
margin-bottom: 16px;
line-height: 1;"><br>
												Your Order is on hold awaiting payment
											</p>
											
											<font size="2" face="Arial" style="color:#000;">
											
											<span lang="en-au">Thank you for your order! Before we are able to ship your order payment is
											<br>
											required.Please transfer funds using the details shown below.
											</font></p>
                                            
        <table border="1" width="449" id="table7" bordercolor="#000000" style="border-collapse: collapse; margin-bottom:20px;" cellpadding="2">
			<tr>
				<td bordercolor="#000000" height="20" colspan="3" style="border-width: 1px;background-color: #DC133C;" class="style7">
				<font face="Arial" size="2" color="#FFFFFF">Bank Transfer Details</font></td>
			</tr>
            <tr>
            <td style="padding:12px;">
            	<p style="font-size:13px; margin-top:5px; margin-bottom:5px;"><b>Total Amount :</b>&#36; $OrderTotalAmount$ </p> 
                <p style="font-size:13px; margin-top:5px; margin-bottom:5px;"><b>BSB :</b> 062-105</p> 
                <p style="font-size:13px; margin-top:5px; margin-bottom:5px;"><b>Account No :</b> 1006-4018</p> 
                <p style="font-size:13px; margin-top:5px; margin-bottom:5px;"><b>Payment Ref :</b> WES$InvoiceNo$</p> 
                <p style="font-size:13px; margin-top:5px; margin-bottom:5px;"><b>Account Name:</b> WES Components Pty Ltd</p> 
                <p style="font-size:13px; margin-top:5px; margin-bottom:5px;"><b>Swift / BIC Code :</b> CTBAAU2S </p> 
                
                <p style="font-size:12px; margin-top:20px; margin-bottom:5px;">Important. Please include the shown payment Ref. No as your payment description for fast processing.</p>   
            </td>
            </tr>
            
        </table>
        
        
		<table border="1" width="449" id="table7" bordercolor="#000000" style="border-collapse: collapse" cellpadding="2">
			<tr>
				<td bordercolor="#000000" height="20" colspan="3" style="border-width: 1px;background-color: #0092C8;" class="style7">
				<font face="Arial" size="2" color="#FFFFFF">Order Information</font></td>
			</tr>
			<tr>
				<td width="150" bordercolor="#000000" style="height: 20px;border-width: 1px;background-color: #E0E0E0;" class="style10">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt">Date</font></td>
				<td width="150" bordercolor="#000000" style="height: 20px;border-width: 1px;background-color: #E0E0E0;" class="style10">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt"><span lang="en-au">
				Customer&nbsp; Order No</span></font></td>
				<td width="150" bordercolor="#000000" style="height: 20px;border-width: 1px;background-color: #E0E0E0;" class="style10">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt"><span lang="en-au">
				Shipping Method</span></font></td>
			</tr>
			<tr>
				<td bordercolor="#000000" height="20" class="style4">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt">$OrderDate$</font></td>
				<td bordercolor="#000000" height="20" class="style4">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt">$CustOrderNo$</font></td>
				<td bordercolor="#000000" height="20" class="style4" style="width: 151px">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt"><span lang="en-au">
				$ShippingMethod$</span></font></td>
			</tr>
		</table>
											<br>
		<table border="1" width="449" id="table8" bordercolor="#000000" style="border-collapse: collapse" cellpadding="2">
			<tr>
				<td width="450" bordercolor="#000000" height="20" colspan="2" style="font-family: Arial, Helvetica, sans-serif;font-size: x-small;border-width: 1px;background-color: #0092C8;" class="style8">
				<font color="#FFFFFF"><span lang="en-au"  style="font-family: Arial;font-size: 9pt;color: #FFFFFF;">User </span style="font-family: Arial;font-size: 9pt;color: #FFFFFF;">Information</font></td>
			</tr>
			<tr>
				<td bordercolor="#000000" height="20" style="width: 294px;border-width: 1px;background-color: #E0E0E0;" class="style10">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt"><span lang="en-au">
				Created By User</span></font></td>
				<td bordercolor="#000000" height="20" style="width: 294px;border-width: 1px;background-color: #E0E0E0;" class="style10">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt"><span lang="en-au">&nbsp;Submitted 
				By User</span></font></td>
				</tr>
			<tr>
				<td bordercolor="#000000" height="20" style="width: 294px" class="style4">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt">$CreatedBy$
				</font></td>
				<td bordercolor="#000000" height="20" class="style4">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt">$SubmittedBy$ 
				</font></td>
				</tr>
		</table>
											<br>
		<table border="1" width="449" id="table9" bordercolor="#000000" style="border-collapse: collapse" cellpadding="2">
			<tr>
		
				<td bordercolor="#000000" style="width: 294px; height: 20px;border-width: 1px;background-color: #0089BC;" class="style3">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" color="#FFFFFF" style="font-size: 9pt">
				<span lang="en-au">&nbsp;Billing Details</span></font></td>
				<td bordercolor="#000000" style="width: 294px; height: 20px;border-width: 1px;background-color: #0089BC;" class="style3">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" color="#FFFFFF" style="font-size: 9pt">
				<span lang="en-au">&nbsp;Shipping Details</span></font></td>
				</tr>
			<tr>
				<td bordercolor="#000000" height="20" style="width: 294px" class="style6">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt">$BillingAddress$ </font></td>
				<td bordercolor="#000000" height="20" style="width: 302px" class="style6">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt">$ShippingAddress$</font></td>
				</tr>
		</table>
											<br>
											$if(TBT_shippingnotes)$
		  <table border="1" width="449" id="table10" bordercolor="#000000" style="border-collapse: collapse" cellpadding="2">
             <tr>
				<td  bordercolor="#000000" height="20" colspan="2" style="font-family: Arial, Helvetica, sans-serif;font-size: x-small;border-width: 1px;background-color: #0091C7;" class="style1">
				<span lang="en-au" style="font-family: Arial;font-size: 9pt;color: #FFFFFF;" class="style2">Order Comments</span></td>
			</tr>

			<tr>
				<td bordercolor="#000000" height="20"  style="border-width: 1px;background-color: #FFFFFF;" class="style6" colspan="2">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt">$shippingnotes$</font></td>
            </tr> 
  </table>
		<br>									
		$endif$
		<table border="1" width="449" id="table10" bordercolor="#000000" style="border-collapse: collapse" cellpadding="2">
			<tr>
				<td width="450" bordercolor="#000000" height="20" colspan="2"  style="font-family: Arial, Helvetica, sans-serif;font-size: x-small;border-width: 1px;background-color: #0091C7;" class="style1">
				<font color="#FFFFFF"><span lang="en-au"  style="font-family: Arial;font-size: 9pt;color: #FFFFFF;" >Order Contents</span></font></td>
			</tr>
			<tr>
				<td bordercolor="#000000" height="20" style="width: 294px;border-width: 1px;background-color: #E0E0E0;" class="style10">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt"><span lang="en-au">
				Order Code</span></font></td>
				<td width="150" bordercolor="#000000" height="20" style="width: 300px;border-width: 1px;background-color: #E0E0E0;" class="style10">
				<p align="left" style="margin-left: 3px" class="style9">
				<span lang="en-au">QTY</span></td>
				</tr>
			$TBWDataList:{
        $it.TBWDataListItem$}$
		</table>
											<p align="left" style="margin-left: 3px">
											<font size="2" face="Arial">Best Regards,<br>
											WES Team</font></p>
										</td>
					</tr>
					</table>
				</td>
			</tr>
		</table>
		</td>
	</tr>
	</table>

</body>
</html>
