<html>

<head>
<meta http-equiv="Content-Language" content="en-us">
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<title>Wes New Customer</title>
<style>
<!--
div.Section1
	{page:Section1;}
.style1 {
				font-family: Arial, Helvetica, sans-serif;
				font-size: x-small;
				border-width: 1px;
				background-color: #0091C7;
}
.style2 {
				font-family: Arial;
				font-size: 9pt;
				color: #FFFFFF;
}
.style3 {
				border-width: 1px;
				background-color: #0089BC;
}
.style4 {
				border-width: 1px;
}
.style6 {
				border-width: 1px;
				background-color: #FFFFFF;
}
.style7 {
				border-width: 1px;
				background-color: #0092C8;
}
.style8 {
				font-family: Arial, Helvetica, sans-serif;
				font-size: x-small;
				border-width: 1px;
				background-color: #0092C8;
}
.style9 {
				font-family: Arial;
				font-size: 9pt;
}
.style10 {
				border-width: 1px;
				background-color: #E0E0E0;
}
-->
</style>
</head>

<body rightmargin="0">
		<table cellpadding="0" width="527" height="520" style="border-collapse: collapse" border="1" bordercolor="#000000" cellspacing="0">
	<tr>
		<td valign="top" height="64" width="525">
		<img alt="WES" src="http://wes.com.au/images/wes_orderpending.gif" width="525" height="72"></td>
	</tr>
	<tr>
		<td valign="top" height="449" width="525">
		<table cellpadding="0" cellspacing="0" border="0" width="490" height="439">
			<!-- MSCellFormattingTableID="2" -->
			<tr>
				<td height="439" width="490">
				<!-- MSCellFormattingType="content" -->
				<table border="0" width="468" height="400" cellpadding="10" cellspacing="0">
					<tr>
						<td valign="top" width="448">
											<p align="left" style="margin-left: 3px">
											<i><b><font face="Arial" size="4">
											<span lang="en-au">Pending 
											Order - </span>WES Australasia</font></b></i><font size="2" face="Arial"><br>
											<br>
											<span lang="en-au">Thanks for your 
											order. Just a friendly reminder 
											there is now a Pending Order on the 
											system. This order is now waiting 
											for approval before being processed. 
											Please login to the My Account Area 
											&gt; Pending Orders to change or submit 
											the order for processing.<br>
											<br>
											<a href="$PendingOrderurl$">$PendingOrderurl$</a></span></font></p>
		<table border="1" width="449" id="table7" bordercolor="#000000" style="border-collapse: collapse" cellpadding="2">
			<tr>
				<td bordercolor="#000000" height="20" colspan="3" style="border-width: 1px;background-color: #0092C8;" class="style7">
				<font face="Arial" size="2" color="#FFFFFF">Order Information</font></td>
			</tr>
			<tr>
				<td width="150" bordercolor="#000000" style="height: 20px;border-width: 1px;background-color: #E0E0E0;" class="style10">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt">Date</font></td>
				<td width="150" bordercolor="#000000" style="height: 20px;border-width: 1px;background-color: #E0E0E0;" class="style10">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt"><span lang="en-au">
				Customer&nbsp; Order No</span></font></td>
				<td bordercolor="#000000" style="height: 20px; width: 151px;border-width: 1px;background-color: #E0E0E0;" class="style10">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt"><span lang="en-au">
				Shipping Method</span></font></td>
			</tr>
			<tr>
				<td bordercolor="#000000" height="20" class="style4">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt">$OrderDate$</font></td>
				<td bordercolor="#000000" height="20" class="style4">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt">$CustOrderNo$</font></td>
				<td bordercolor="#000000" height="20" class="style4" style="width: 151px">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt"><span lang="en-au">
				$ShippingMethod$</span></font></td>
			</tr>
		</table>
											<br>
		<table border="1" width="449" id="table8" bordercolor="#000000" style="border-collapse: collapse" cellpadding="2">
			<tr>
				<td width="450" bordercolor="#000000" height="20" colspan="2" style="font-family: Arial, Helvetica, sans-serif;font-size: x-small;border-width: 1px;background-color: #0092C8;" class="style8">
				<span lang="en-au" style="font-family: Arial;font-size: 9pt;color: #FFFFFF;" class="style2">User Information</span></td>
			</tr>
			<tr>
				<td bordercolor="#000000" height="20" style="width: 294px;border-width: 1px;background-color: #E0E0E0;" class="style10">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt"><span lang="en-au">
				Created By User</span></font></td>
				<td  bordercolor="#000000" height="20" style="width: 294px;border-width: 1px;background-color: #E0E0E0;" class="style10">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt"><span lang="en-au">&nbsp;Submitted 
				By User</span></font></td>
				</tr>
			<tr>
				<td bordercolor="#000000" height="20" style="width: 294px" class="style4">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt">$CreatedBy$
				</font></td>
				<td bordercolor="#000000" height="20" class="style4">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt">$SubmittedBy$
				</font></td>
				</tr>
		</table>
											<br>
		<table border="1" width="449" id="table9" bordercolor="#000000" style="border-collapse: collapse" cellpadding="2">
			<tr>
				<td bordercolor="#000000" style="width: 294px; height: 20px;border-width: 1px;background-color: #0089BC;" class="style3">
				<p align="left" style="margin-left: 3px;font-family: Arial;font-size: 9pt;color: #FFFFFF;" class="style2">
				<span lang="en-au">Billing Details</span></td>
				<td bordercolor="#000000" style="height: 20px; width: 294px;border-width: 1px;background-color: #0089BC;" class="style3">
				<p align="left" style="margin-left: 3px">
				<span lang="en-au" style="font-family: Arial;font-size: 9pt;color: #FFFFFF;" class="style2">&nbsp;Shipping Details</span></td>
				</tr>
			<tr>
				<td bordercolor="#000000" height="20" style="width: 294px" class="style6">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt">
				$BillingAddress$
				</font></td>
				<td bordercolor="#000000" height="20" style="width: 302px" class="style6">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt">$ShippingAddress$</font></td>
				</tr>
		</table>
											<br>


											 $if(TBT_shippingnotes)$
  <table border="1" width="449" id="table10" bordercolor="#000000" style="border-collapse: collapse" cellpadding="2">
             <tr>
				<td width="450" bordercolor="#000000" height="20" colspan="2" style="font-family: Arial, Helvetica, sans-serif;font-size: x-small;border-width: 1px;background-color: #0091C7;" class="style1">
				<span lang="en-au" style="font-family: Arial;font-size: 9pt;color: #FFFFFF;" class="style2">Order Comments</span></td>
			</tr>

			<tr>
				<td bordercolor="#000000" height="20"  style="border-width: 1px;background-color: #FFFFFF;" class="style6" colspan="2">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt">$shippingnotes$</font></td>
            </tr> 
  </table>
    <br>
	$endif$



		<table border="1" width="449" id="table10" bordercolor="#000000" style="border-collapse: collapse" cellpadding="2">
			<tr>
			    <td width="450" bordercolor="#000000" height="20" colspan="2" style="font-family: Arial, Helvetica, sans-serif;font-size: x-small;border-width: 1px;background-color: #0091C7;" class="style1">
				<span lang="en-au" style="font-family: Arial;font-size: 9pt;color: #FFFFFF;" class="style2">Order Contents</span></td>

			</tr>
			<tr>
				<td bordercolor="#000000" height="20" style="width: 294px;border-width: 1px;background-color: #E0E0E0;" class="style10">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt"><span lang="en-au">
				Order Code</span></font></td>
				<td width="150" bordercolor="#000000" height="20" style="width: 300px;border-width: 1px;background-color: #E0E0E0;" class="style10">
				<p align="left" style="margin-left: 3px" class="style9">
				<span lang="en-au">QTY</span></td>
				</tr>
			
				$TBWDataList:{
        $it.TBWDataListItem$}$
		</table>
											<p align="left" style="margin-left: 3px">
											<font size="2" face="Arial">Best Regards,<br>
											WES Team</font></p>
										</td>
					</tr>
					</table>
				</td>
			</tr>
		</table>
		</td>
	</tr>
	</table>
		</body>

</html>