<tr>
  <td style="padding: 0px 0px 0px 3px; margin: 0px; border: 1px solid #000000; width: 225px; font-family: arial, Helvetica, sans-serif; font-size: 9pt; border-collapse: collapse; height: 20px;">
    $Code$
  </td>
  <td style="padding: 0px 0px 0px 3px; margin: 0px; border: 1px solid #000000; width: 225px; font-family: arial, Helvetica, sans-serif; font-size: 9pt; border-collapse: collapse; height: 20px;">
    $Qty$
  </td>
</tr>
