<tr>
  <td style="border-style: solid; border-width: 1px; height: 25px">
    <p  style="margin-left: 3px; font-family: arial, Helvetica, sans-serif; font-size: 9pt;" align="left">
      $Code$
    </p>
     
  </td>
  <td style="border-style: solid; border-width: 1px; height: 25px">
    <p style="margin-left: 3px; font-family: arial, Helvetica, sans-serif; font-size: 9pt;" align="left">
     $Qty$
      </p>
  </td>
</tr>
