<html>

<head>
<meta http-equiv="Content-Language" content="en-us">
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<title>Wes New Customer</title>
</head>

<body rightmargin="0">
		<table cellpadding="0" width="527" height="520" style="border-collapse: collapse" border="1" bordercolor="#000000" cellspacing="0">
	<tr>
		<td valign="top" height="64" width="525">
		<img alt="WES" src="http://wes.com.au/images/Address-RequestForm.gif" width="525" height="71"></td>
	</tr>
	<tr>
		<td valign="top" height="449" width="525">
		<table cellpadding="0" cellspacing="0" border="0" width="490" height="439">
			<!-- MSCellFormattingTableID="2" -->
			<tr>
				<td height="439" width="490">
				<!-- MSCellFormattingType="content" -->
				<table border="0" width="468" height="400" cellpadding="10" cellspacing="0">
					<tr>
						<td valign="top" width="448">

		<table border="1" width="449" id="table10" bordercolor="#000000" style="border-collapse: collapse" cellpadding="2">
			<tr>
				<td width="450" bordercolor="#000000" height="20" colspan="2"  style="font-family: Arial, Helvetica, sans-serif;font-size: x-small;border-width: 1px;background-color: #0091C7;" class="style1">
				<font color="#FFFFFF"><span lang="en-au"  style="font-family: Arial;font-size: 9pt;color: #FFFFFF;" >Update Address</span></font></td>
			</tr>
			
			<tr>
				<td bordercolor="#000000" height="20" style="width: 50%" class="style4">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt">CUSTOMER NO
				</font></td>
				<td bordercolor="#000000" height="20" class="style4">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt">$CUSTOMER_NO$
				</font></td>
				</tr>

		<!--		<tr>
				<td bordercolor="#000000" height="20" style="width: 50%" class="style4">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt">REQUESTED BY
				</font></td>
				<td bordercolor="#000000" height="20" class="style4">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt">$REQUESTED_BY$
				</font></td>
				</tr>

			<tr>
				<td bordercolor="#000000" height="20" style="width: 50%" class="style4">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt">USER ID
				</font></td>
				<td bordercolor="#000000" height="20" class="style4">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt">$USER_ID$
				</font></td>
				</tr>  -->

				<tr>
				<td bordercolor="#000000" height="20" style="width: 50%" class="style4">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt">ACCOUNT / COMPANY NAME
				</font></td>
				<td bordercolor="#000000" height="20" class="style4">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt">$BUSINESS_NAME$
				</font></td>
				</tr>
				
				<tr>
				<td bordercolor="#000000" height="20" style="width: 50%" class="style4">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt">ADDRESS LINE 1
				</font></td>
				<td bordercolor="#000000" height="20" class="style4">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt">$STREET_ADDRESS1$
				</font></td>
				</tr>

				 $if(STREET_ADDRESS2_SHOW)$
				<tr>
				<td bordercolor="#000000" height="20" style="width: 50%" class="style4">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt">ADDRESS LINE 2
				</font></td>
				<td bordercolor="#000000" height="20" class="style4">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt">$STREET_ADDRESS2$
				</font></td>
				</tr>
				$endif$

				<tr>
				<td bordercolor="#000000" height="20" style="width: 50%" class="style4">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt">SUBURB
				</font></td>
				<td bordercolor="#000000" height="20" class="style4">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt">$TOWN$
				</font></td>
				</tr>

				<tr>
				<td bordercolor="#000000" height="20" style="width: 50%" class="style4">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt">STATE
				</font></td>
				<td bordercolor="#000000" height="20" class="style4">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt">$STATE$
				</font></td>
				</tr>

				<tr>
				<td bordercolor="#000000" height="20" style="width: 50%" class="style4">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt">POST CODE
				</font></td>
				<td bordercolor="#000000" height="20" class="style4">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt">$ZIPCODE$
				</font></td>
				</tr>

				<tr>
				<td bordercolor="#000000" height="20" style="width: 50%" class="style4">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt">COUNTRY
				</font></td>
				<td bordercolor="#000000" height="20" class="style4">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt">$COUNTRY$
				</font></td>
				</tr
				<tr>
				<td bordercolor="#000000" height="20" style="width: 50%" class="style4">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt">ATTN / RECEIVER NAME
				</font></td>
				<td bordercolor="#000000" height="20" class="style4">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt">$RECEIVER_NAME$
				</font></td>
				</tr>
				<tr>
					<td bordercolor="#000000" height="20" style="width: 50%" class="style4">
					<p align="left" style="margin-left: 3px">
					<font face="Arial" style="font-size: 9pt">PHONE NUMBER
					</font></td>
					<td bordercolor="#000000" height="20" class="style4">
					<p align="left" style="margin-left: 3px">
					<font face="Arial" style="font-size: 9pt">$PHONE_NUMBER$
					</font></td>
				</tr>
				<tr>
				<td bordercolor="#000000" height="20" style="width: 50%" class="style4">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt">DELIVERY INSTRUCTIONS
				</font></td>
				<td bordercolor="#000000" height="20" class="style4">
				<p align="left" style="margin-left: 3px">
				<font face="Arial" style="font-size: 9pt">$DELIVERY_INST$
				</font></td>
				</tr>
				
		</table>
		<div>
					<p style="margin-bottom: 0;">Requested by :  $REQUESTED_BY$</p>
					<p style="margin: 0;">User Id : $USER_ID$</p>
				</div>
	<p align="left" style="margin-left: 3px">
	<font size="2" face="Arial">Best Regards,<br>
	WES Team</font></p>
</td>
					</tr>
					</table>
				</td>
			</tr>
		</table>
		</td>
	</tr>
	</table>
		</body>

</html>