<div class="container_cmn" >
  <div class="container12">
    <div class="span12 box2" style="margin-left:6px;width: 946px;">
      <div class="fourbox">
        <h3 class="title5">PRODUCT CATEGORIES</h3>
        <ul class="list1" style="list-style: none outside none;border: 0 none;font-size: 100%;margin: 0;padding: 0;">       
            $TBWDataList:{
            $it.TBWDataListItem$}$          
        </ul>
      </div>
      <div class="fourbox">
        <h3 class="title5">MY ACCOUNT</h3>
        <ul class="list1" style="list-style: none outside none;border: 0 none;font-size: 100%;margin: 0;padding: 0;">
          <li>
           
            <a href="EditUserProfile.aspx" >View Profile</a>
         
          </li>
          <li >
            <a href="changePassword.aspx" >Change Password</a>
          </li>
          <li >
            <a href="changeUsername.aspx" >Change Username</a>
          </li>
          <li >
            <!--<a href="Orders.aspx?ViewType=HISTORY" >Order History</a>-->
            <a href="OrderHistory.aspx" >Order History</a>
            
          </li>

        </ul>
      </div>
      <div class="fourbox">
        <h3 class="title5">COMPANY INFO</h3>
        <ul class="list1" style="list-style: none outside none;border: 0 none;font-size: 100%;margin: 0;padding: 0;">
          <li >
            <a href="aboutus.aspx" class="tx_4">About Us</a>
          </li>
          <li >
            <a href="contactus.aspx" class="tx_4">Contact Us</a>
          </li>
          <li >
            <a href="Termsandconditions.aspx" class="tx_4">Terms and Conditions</a>
          </li>
          <li >
            <a href="privacepolicy.aspx" class="tx_4">Privacy Policy</a>
          </li>
          <li >
            <a href="OnlineCatalogue_price.aspx" class="tx_4">Catalogue Download</a>
          </li>
          <li >
            <a href="OnlineCatalogue_price.aspx" class="tx_4">News Letter Download</a>
          </li>
          <li >
            <a href="http://www.wes.com.au/info/" class="tx_4">WES Electronic News</a>
          </li>
        </ul>
      </div>
    </div>
    <div style="color: rgb(241, 241, 241);" align="left">&nbsp;&nbsp;V4.12</div>
  </div>  
    
</div >