<table>
<tr>
  <td height="10"></td>
</tr>
</table>
<table width="558" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td height="30" background="images/23.gif">
      <table width="540" border="0" align="center" cellpadding="0" cellspacing="0">
        <tr>
          <td height="30" class="tx_1">
            <strong> PRODUCTS SEARCH</strong>
          </td>          
        </tr>
      </table>
    </td>
  </tr>
  <tr>
    <td height="126" align="center" class="back_9">
      <div style="width:588px; height:150px; overflow:auto; ">
        <table width="550" border="0" align="center" cellpadding="10" cellspacing="0" class="tx_1">
          <tr>
            $TBWDataList:{
            $it.TBWDataListItem$}$
            <td width="115" valign="bottom">
              <input name="button2" type="button" class="form_boton" id="button2" value="Apply Filters"  onclick="GetSelectedItemsFilter();"/>
            </td>
          </tr>
        </table>
      </div>
    </td>
  </tr>
</table>
<!--<TABLE class="SearchResultsTable">
    <TBODY>
      <TR>
        <TD>
          <SPAN class="bold">Filter by product details</SPAN>
          <SPAN class="bold"></SPAN>
          <BR/>
          <BR/>
          <TABLE>
            <TBODY>
              <TR>
                <TD>
                  <TABLE class="bottom"
                  style="BORDER-COLLAPSE: collapse" cellSpacing="0" border="0">
                    <TBODY>
                      <TR>
                        $TBWDataList:{
                        $it.TBWDataListItem$}$
                      </TR>
                    </TBODY>
                  </TABLE>

                  <TABLE style="WIDTH: 100%">
                    <TBODY>
                      <TR>
                        <TD style="WIDTH: 100px">&nbsp;</TD>
                        <TD style="WIDTH: 100px"></TD>
                        <TD vAlign="bottom"></TD>
                      </TR>
                      <TR>
                        <TD style="WIDTH: 100px">
                          <input class="button-white" type="submit" value="Apply Filters" name="ApplyFilter" onclick="GetSelectedItems();"/>
                        </TD>
                        <TD style="WIDTH: 100px"></TD>
                        <TD vAlign="bottom"></TD>
                      </TR>
                    </TBODY>
                  </TABLE>
                </TD>
              </TR>
            </TBODY>
          </TABLE>
        </TD>
      </TR>
    </TBODY>
  </TABLE>-->
