<td>
  <table>
    <tr>
      <td width="287" valign="top">
        <p>
          <strong>$TBW_ATTRIBUTE_NAME$</strong>
          <br/>
          <SELECT multiple="multiple"  id="$TBW_ATTRIBUTE_ID$"  style="width: 200px; overflow:auto;" size="7" name="lst1">
            $TBWDataList:{
            $it.TBWDataListItem$}$
          </SELECT>
        </p>
      </td>
    </tr>
    <tr>
      <td align="left">&nbsp;
        <a href="#" onclick="Reset();">Reset</a>
      </td>
    </tr>
  </table>
</td>
                       

