<table width="96%" border="0" cellpadding="0" cellspacing="0">
  <tr>
    <td>
      <table width="100%" border="0" cellspacing="0" cellpadding="5">
        <tr>
          <td class="tx_1" align="left">
            <a href="home.aspx" style="color:#0099FF" class="tx_3">Home</a>
            <font style="font-family: Arial, Helvetica, sans-serif; font-weight:bolder; font-size: small; font-style: normal"> / </font>Privacy Policy
          </td>
        </tr>
        <tr>
          <td class="tx_3">
            <hr>
          </td>
        </tr>
      </table>
    </td>
  </tr>
  <tr>
    <td height="30" class="tx_7" align="left">PRIVACY POLICY</td>
  </tr>
  <tr>
    <td class="tx_1" align="left">Find out more about WES. If you can't find the information you need, please use the Make an Enquiry page or phone 1100 13 933 and get help from a Customer Service representative.</td>
  </tr>
  <tr>
    <td align="center" valign="top">&nbsp;</td>
  </tr>
  <tr>
    <td align="center" valign="top">
      <table width="558" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td height="30" background="images/17.gif">
            <table width="540" border="0" align="center" cellpadding="0" cellspacing="0">
              <tr>
                <td height="30" class="tx_6" align="left">INFORMATION</td>
                <td align="right">
                  <img src="images/ico_11.gif" width="14" height="17">
                </td>
              </tr>
            </table>
          </td>
        </tr>
        <tr>
          <td class="back_table_center1">
            <table width="540" border="0" align="center" cellpadding="10" cellspacing="0" class="tx_1">
              <tr>
                <td valign="top" align="left">
                  <p>
                    <strong>
                      <br/>
                              Privacy Statement
                    </strong>
                    <br/>
                      Shoplet.com respects your privacy. For detailed information about our privacy policy, please click here.<br>
                        <br/>
                            </p>
                  <p>
                    <strong>Protecting your credit card</strong>
                    <br/>
                                Our commerce application is built on Microsoft's Commerce Server. Provided you are using an SSL-enabled (Secure Socket Layering) web browser, such as Netscape's Navigator or Microsoft's Internet Explorer, you'll be able to conduct end-to-end encrypted transactions without fear of an unauthorized third party obtaining your credit card information.
                  </p>
                  <p>
                    <strong>
                      <br/>
                                Disclaimer
                    </strong>
                    <br/>
                                To read our full disclaimer please click here.
                  </p>
                  <p>
                    <strong>
                      <br/>
                                Copyright
                    </strong>
                    <br>
                                All content, unless noted otherwise, is copyright &copy; 1994-2006 by Shoplet.com. All rights reserved. For detailed copyright information, please click here.
                  </p>
                </td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
      <br/>
      <br/>
      <br/>
      <br/>
      <br/>
      <br/>
    </td>
  </tr>
</table>











