<table width="96%" border="0" cellpadding="0" cellspacing="0">
  <tr>
    <td>
      <table width="100%" border="0" cellspacing="0" cellpadding="5">
        <tr>
          <td class="tx_1" align="left">
            <a href="home.aspx" style="color:#0099FF" class="tx_3">Home</a>
            <font style="font-family: Arial, Helvetica, sans-serif; font-weight:bolder; font-size: small; font-style: normal"> / </font>Terms and Conditions
          </td>
        </tr>
        <tr>
          <td class="tx_3">
            <hr/>
          </td>
        </tr>
      </table>
    </td>
  </tr>
  <tr>
    <td height="30" align="left" class="tx_7">TERMS AND CONDITIONS</td>
  </tr>
  <tr>
    <td align="center" valign="top">&nbsp;</td>
  </tr>
  <tr>
    <td align="center" valign="top">
      <table width="558" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td height="30" background="images/17.gif">
            <table width="540" border="0" align="center" cellpadding="0" cellspacing="0">
              <tr>
                <td height="30" class="tx_6" align="left">GENERAL INFORMATION AND CONDITIONS
                </td>
                <td align="right">
                  <img src="images/ico_11.gif" width="14" height="17"/>
                </td>
              </tr>
            </table>
          </td>
        </tr>
        <tr>
          <td class="back_table_center3" valign="top">
            <table width="540" border="0" align="center" cellpadding="10" cellspacing="0" class="tx_1" >
              <tr>
                <td valign="top" align="left">
                  <p>
                    <strong>
                      <br/>
                      WES AUSTRALASIA:
                    </strong>                    
                     &nbsp;WES Australasia is an Independent Australian Company dedicated to the Electronics Industry. Our aim is to give you the Best possible service at Competitive Prices.
                    <br/>
                    <br/>
                            </p>
                  <p>
                    <strong>THE PRODUCTS:</strong>

                    &nbsp;Goods supplied are sourced from numerous sources locally and overseas. It is our policy to purchase from reputable suppliers in order to assure that the products are of the highest quality.
                    <br/>
                  <br/>

                </p>
                  <p>
                    <strong>
                      <br/>
                      PRICES:
                    </strong>
                        &nbsp;The prices shown on the Web Site and in Catalogue are current at the time of display / print however there are many factors which can effect cost prices including material cost rises, shortages and currency variations, etc. The intention is to maintain the published prices for the term of the catalogue however this may not be possible in all cases. Prices are therefore subject to change without notice. All prices EXCLUDE GST.
                    <br/>
                        <br/>
                </p>
                  <p>
                    <strong>
                      <br/>
                      OWNERSHIP OF GOODS:
                    </strong>
                    &nbsp; Goods and Services supplied by WES remain the property of WES, in accordance with the retention of title clause, until goods supplied are paid for by the customer.
                    <br/>
                    <br/>
                  </p>
                  <p>
                    <strong>
                      <br/>
                      LIABILITY:
                    </strong>
                    &nbsp; The use of the products purchased is beyond our control or supervision. We therefore cannot accept any liability for losses or consequential damage to any goods or equipment. Although WES does not manufacture the goods sold, we do ensure that the products are of the highest quality however in a rare event of a product being faulty, we will make a claim to our supplier on your behalf. Each supplier have their own policy on returned goods which range from repair to replacement after inspection.
                    <br/>
                    <br/>
                  </p>
                  <p>
                    <strong>
                      <br/>
                      DANGEROUS GOODS:
                    </strong>
                    &nbsp; Orders with goods which are restricted, such as some batteries, aerosols or isopropanol products must be sent by road.
                    <br/>
                    <br/>
                  </p>
                  <p>
                    <strong>
                      <br/>
                      BACK ORDERS:
                    </strong>
                    &nbsp; Goods not in stock will be automatically back ordered and shipped when available with your next order unless otherwise requested..
                    <br/>
                    <br/>
                  </p>
                  <p>
                    <strong>
                      <br/>
                      GOODS RETURNED:
                    </strong>
                    &nbsp; Please, it is essential you obtain a Return Authorisation number ( RA ) before returning any goods. All goods to be returned must be freight prepaid and accompanied with a copy of the original purchase invoice. The RA number must be clearly written on the parcel. Parcels returned without an RA will not be accepted or will be returned. Faulty goods will be returned to our supplier for their determination. Faulty goods will be replaced or repaired only, not credited. Goods purchased incorrectly or no longer required are not able to be returned. For goods that are returned, they must be sent back in the original packaging and same as new condition they were received in; that is no price tags, shipping labels, tape / text marks, physical damage to box, etc. Please ensure that all items are returned including any parts, accessories and instructions that were included with the original product.
                    <br/>
                    <br/>
                  </p>
                  <p>
                    <strong>
                      <br/>
                      ERRORS/OMISSIONS:
                    </strong>
                    &nbsp;
                    Due to the large product range shown on our web site and within our catalogues, it is possible that mistakes exist. All care has been taken to eliminate errors, but no responsibility can be accepted. Therefore, we recommend that this catalogue be used as a guide only. Please tell us if you discover any discrepancies.
                    <br/>
                    <br/>
                  </p>

                  <p>
                    <strong>
                      <br/>
                      DELIVERY:
                    </strong>
                    &nbsp;Delivery and handling charges apply to all orders. The prices quoted are for deliveries within Australia using our selected transport companies. Customers are welcomed to send their own couriers to pick up the goods. NO delivery or handling charge applies if goods are picked up either in person or with your nominated transport company.


                    <br/>
                    <br/>
                  </p>
                  <p>
                    <strong>
                      <br/>
                      MAIL:
                    </strong>
                    &nbsp;&#36;8.75 ex GST for parcels under 250 grams, actual or cube, whichever is greater.
                    <br/>
                    <br/>
                  </p>
                  <p>
                    <strong>
                      <br/>
                      PO BOX DELIVERIES:
                    </strong>
                    &nbsp;Must use Australia Post, charges will be calculated based on our cost if over 250 grams
                    <br/>
                    <br/>
                  </p>
                  <p>
                    <strong>
                      <br/>
                      EXPRESS POST:
                    </strong>
                    &nbsp;Will be calculated based on our cost.
                    <br/>
                    <br/>
                  </p>
                  <p>
                    <strong>
                      <br/>
                      LOCAL DELIVERY:
                    </strong>
                    &nbsp;&#36;8.75 ex GST - Sydney Metropolitan Road Service, this is an overnight service and the maximum payable regardless of the weight of the order or the number of parcels.
                    <br/>
                    <br/>
                  </p>
                  <p>
                    <strong>
                      <br/>
                      AUSTRALIA WIDE DELIVERY *
                    </strong>
                    &nbsp;&#36;10.75 ex GST- Overnight Service, this covers parcels that weigh up to 3kg ( actual or cubic ) only. Where logistics allow, this is usually an overnight service. Parcels over 3kg will be sent by the most economical way, usually by road. Please allow extra time for delivery. If air service is definitely required please contact us and we will provide costing based on your requirements.
                    <br/>
                     <strong>* Please Note:</strong>&nbsp; The above prices are for standard products to standard delivery areas. Bulky Products and delivery to Remote / Special areas will incur additional charges.
                    <br/>
                    <br/>
                  </p>
                  <p>
                    <strong>
                      <br/>
                      PICK UPS:
                    </strong>
                    &nbsp;Goods can be picked up from our premises from 8.30AM to 5.00PM Monday to Friday and from 9AM till 4PM on Saturday. In order to avoid delays it is recommended that you place your order prior to attending to ensure that goods are ready to pick up from our store. If you are picking up on Saturday please place your order on Friday as the WES call centre is closed on Saturday. If you need to contact us on Saturday please call us using the following number: 02-9798-9233.
                    <br/>
                    <br/>
                  </p>
                  <p>
                    <strong>
                      <br/>
                      DROP SHIPMENT:
                    </strong>
                    &nbsp;We are able to offer Drop Shipment Services. Please contact us for further information and details if you require this service.
                    <br/>
                    <br/>
                  </p>

                
               
                  
                </td>
              </tr>
            </table>
          </td>
        </tr>
      </table>     
    </td>
  </tr>
</table>











