<table width="96%" border="0" cellpadding="0" cellspacing="0">
  <tr>
    <td>
      <table width="100%" border="0" cellspacing="0" cellpadding="5">
        <tr>
          <td class="tx_1" align="left">
            <a href="#" class="tx_3" style="color:#0099ff">Home</a><font style="font-family: Arial, Helvetica, sans-serif; font-weight:bolder; font-size: small; font-style: normal"> / </font>SSL Security Seal
          </td>
        </tr>
        <tr>
          <td class="tx_3">
            <hr/>
          </td>
        </tr>
      </table>
    </td>
  </tr>
  <tr>
    <td height="30" class="tx_7" align="left">
      SSL SECURITY SEAL<br/>
    </td>
  </tr>
  <tr>
    <td class="tx_1" align="left">Read about our commitment to ensuring the privacy of your information. If you can't find the information you need, please use the Make an Enquiry page or phone 1100 13 900 and get help from a Customer Service representative.</td>
  </tr>
  <tr>
    <td align="center" valign="top">&nbsp;</td>
  </tr>
  <tr>
    <td valign="top" class="tx_1">
      <table width="558" border="0" align="center" cellpadding="0" cellspacing="0">
        <tr>
          <td height="30" background="images/17.gif">
            <table width="540" border="0" align="center" cellpadding="0" cellspacing="0">
              <tr>
                <td height="30" class="tx_6" align="left">PAGE INDEX</td>
                <td align="right">
                  <img src="images/ico_11.gif" width="14" height="17"/>
                </td>
              </tr>
            </table>
          </td>
        </tr>
        <tr>
          <td class="back_table_center1">
            <table width="540" border="0" align="center" cellpadding="10" cellspacing="0" class="tx_3">
              <tr>
                <td width="250" valign="top" align="left">
                  <p>
                      <a href="#" class="tx_3">1. How We Handle Customer Information</a><br>
                      <br/>
                        <a href="#" class="tx_3"> 2. How We Protect Customer Information</a><br>
                          <br/>
                            <a href="#" class="tx_3">3. How We Use Cookies &amp; Other Technologies</a>
                  </p>
                </td>
                <td valign="top" class="border_3" align="left">
                  <p>
                     <a href="#" class="tx_3">4. How We Handle Marketing Communications</a><br>
                      <br/>
                        <a href="#" class="tx_3">5. How to Update Your Information</a><br>
                          <br/>
                            <a href="#" class="tx_3">6. Coles Group Limited Privacy Policy</a>
                  </p>
                </td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
      <br/>
        <br/>
          <br/>
            <p align="left">
              <strong>1. How To...</strong>
            </p>
            <p align="left">We do not collect personal information when you visit our site unless you log on, place an order or register with us.</p>
            <p align="left">
              When you place an order you will be asked for the following personal information: your name, e-mail address, mailing address, delivery address and any special delivery instructions, phone number and Fly Buys number. We may share this information, and only that information which is absolutely necessary, with those third parties that are involved in the processing of your order. For example, the financial institution that issued your credit card and the shipping carrier that delivers your order.<br>
                        Harris Technology is committed to reducing the amount of fraud it faces. Our policy is that we will prosecute any cases of fraud that we identify. As a first time customer, you may receive a telephone call or email requesting more information/proof to confirm the details that you have supplied to us. If any of the information you supply is found to be false or misleading, we will, if we deem it appropriate, report this to the appropriate authorities for them to prosecute.</p>
            <p align="left">
              <strong>2. How To...</strong>
            </p>
            <p align="left">We do not collect personal information when you visit our site unless you log on, place an order or register with us.</p>
            <p align="left">
              When you place an order you will be asked for the following personal information: your name, e-mail address, mailing address, delivery address and any special delivery instructions, phone number and Fly Buys number. We may share this information, and only that information which is absolutely necessary, with those third parties that are involved in the processing of your order. For example, the financial institution that issued your credit card and the shipping carrier that delivers your order.<br>
                        Harris Technology is committed to reducing the amount of fraud it faces. Our policy is that we will prosecute any cases of fraud that we identify. As a first time customer, you may receive a telephone call or email requesting more information/proof to confirm the details that you have supplied to us. If any of the information you supply is found to be false or misleading, we will, if we deem it appropriate, report this to the appropriate authorities for them to prosecute.</p>
            <p align="left">
              <strong>3. How To...</strong>
            </p>
            <p align="left">We do not collect personal information when you visit our site unless you log on, place an order or register with us.</p>
            <p align="left">
              When you place an order you will be asked for the following personal information: your name, e-mail address, mailing address, delivery address and any special delivery instructions, phone number and Fly Buys number. We may share this information, and only that information which is absolutely necessary, with those third parties that are involved in the processing of your order. For example, the financial institution that issued your credit card and the shipping carrier that delivers your order.<br>
                        Harris Technology is committed to reducing the amount of fraud it faces. Our policy is that we will prosecute any cases of fraud that we identify. As a first time customer, you may receive a telephone call or email requesting more information/proof to confirm the details that you have supplied to us. If any of the information you supply is found to be false or misleading, we will, if we deem it appropriate, report this to the appropriate authorities for them to prosecute.</p>
            <p align="left">
              <strong>4. How To...</strong>
            </p>
            <p align="left">We do not collect personal information when you visit our site unless you log on, place an order or register with us.</p>
            <p align="left">
              When you place an order you will be asked for the following personal information: your name, e-mail address, mailing address, delivery address and any special delivery instructions, phone number and Fly Buys number. We may share this information, and only that information which is absolutely necessary, with those third parties that are involved in the processing of your order. For example, the financial institution that issued your credit card and the shipping carrier that delivers your order.<br>
                        Harris Technology is committed to reducing the amount of fraud it faces. Our policy is that we will prosecute any cases of fraud that we identify. As a first time customer, you may receive a telephone call or email requesting more information/proof to confirm the details that you have supplied to us. If any of the information you supply is found to be false or misleading, we will, if we deem it appropriate, report this to the appropriate authorities for them to prosecute.</p>
            <br/>
              <br/>
                <br/>
    </td>
  </tr>
</table>