<table width="180" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td class="back_5">
      <table width="160" border="0" align="center" cellpadding="0" cellspacing="0">
        <tr>
          <td height="30" class="tx_6" align="left">PRODUCT HIGHLIGHT</td>
          <td>
            <img src="images/ico_11.gif" width="14" height="17"/>
            </td>
        </tr>
      </table>
    </td>
  </tr>
  <tr>
    <td align="center" valign="bottom" class="back_tb_cost1">
      <br/>
      <a href="$TBT_RHS_LINK$"  alt="">
        <img src="ProdImages/Section11_Images/2CR5.jpg" width="160" height="500" alt=""/>
      </a>
    </td>
  </tr>
</table>