<td>
<table>
<TR><td colspan="2" align="LEFT">
<B>$TBT_ACT_IND$</B></td>
</TR>
<TR>
  <td colspan="2" align="LEFT">
    <B>$TBT_ANSI_BIFMA_CDE$</B>
  </td>
</TR>
<TR>
  <td colspan="2" align="LEFT">
    <B>$TBT_ASM_REQ_IND$</B>
  </td>
</TR>
<TR>
  <td colspan="2" align="LEFT">
    <B>$TBT_BX_GTIN_CDE$</B>
  </td>
</TR>
<TR>
<td align="left">
  <a href="productdetails.aspx?&pid=$TBT_PRODUCT_ID$">$TBT_CAT_NO$</a>
</td><td><font color="red"><B>$TBT_YOURPRICE$</B></font></td>
</TR>
</table>
</td>