<td>
  <table width="100%">
    <TR>      
      <td  align="left" valign="middle" height="30px">
        <a href="productdetails.aspx?cid=$TBT_CATEGORY_ID$&&pid=$TBT_PRODUCT_ID$&&fid=$TBT_FAMILY_ID$">$TBT_CODE$</a>
      </td>
    </TR>
    <TR>
      <td align="left" valign="middle" height="30px">
          <font color="red">
          &#36; $TBT_COST$
          </font>        
      </td>
    </TR>
    <tr>
    <td align="left" width="50px">
      <a href="productdetails.aspx?cid=$TBT_CATEGORY_ID$&&pid=$TBT_PRODUCT_ID$&&fid=$TBT_FAMILY_ID$">
        <img height="50px" width="50px" src="prodimages$TBT_WEB_IMAGE1$"/>
      </a>
    </td>
    </tr>
    <tr>
      <td align="left">
      <a href="OrderDetails.aspx?&bulkorder=1&Pid=$TBT_PRODUCT_ID$&Qty=$TBT_MIN_ORD_QTY$&ORDER_ID=$TBT_ORDER_ID$" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image$TBT_PRODUCT_ID$cp','','images/but_buy2.gif',1)">
        <img src="images/but_buy1.gif" name="Image$TBT_PRODUCT_ID$cp" width="76" height="25" border="0"/>
      </a>
    </td>
    </tr>
  </table>
</td>