<table width="96%" border="0" cellpadding="0" cellspacing="0">
  <tr>
    <td>
      <table width="100%" border="0" cellspacing="0" cellpadding="5">
        <tr>
          <td align="left" class="tx_1">
            <a href="home.aspx" style="color:#0099FF" class="tx_3">Home</a> / Products Compare
          </td>
        </tr>
        <tr>
          <td class="tx_3">
            <hr>
      </td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table width="96%" border="0" cellpadding="0" cellspacing="0">
  <tr>
  <td>
    <table width="100%">
      <TR>
        <td align="left" valign="middle" height="30px">
          <B>Product</B>
        </td>
      </TR>
      <TR>
        <td align="left" valign="middle" height="30px">
          <b>Price</b>          
        </td>
      </TR>
      <tr>
        <td align="left" height="50px" width="50px">
          <b>Image</b>
        </td>
      </tr>
      <tr>
      <td align="center" width="76" height="25">
        
      </td>
    </tr>
    </table>
  </td>  
    $TBWDataList:{
    $it.TBWDataListItem$}$
  </tr>
</table>

