<table width="96%" border="0" cellpadding="0" cellspacing="0">

  <tr>
    <td>
      <table width="100%" border="0" cellspacing="0" cellpadding="5">
        <tr>
          <td align="left" class="tx_1">
            <a href="home.aspx"  style="color:#0099FF"  class="tx_3">Home</a><font style="font-family: Arial, Helvetica, sans-serif; font-weight:bolder; font-size: small; font-style: normal"> / </font>Contact Us
          </td>
        </tr>
        <tr>
          <td class="tx_3">
            <hr>
          </td>

        </tr>
      </table>
    </td>
  </tr>
  <tr>
    <td height="30" align="left" class="tx_7">CONTACT US</td>
  </tr>
  <tr>
    <td align="center" valign="top" class="tx_1">&nbsp;</td>
  </tr>
  <tr>
    <td align="center" valign="top" class="tx_1">
      <table width="558" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td height="30" background="images/17.gif">
            <table width="540" border="0" align="center" cellpadding="0" cellspacing="0">
              <tr>

                <td align="left" height="30" class="tx_6">INFORMATION</td>
                <td align="right">
                  <img src="images/ico_11.gif" width="14" height="17">
                </td>
              </tr>
            </table>
          </td>
        </tr>
        <tr>
          <td class="back_table_center1">
            <br>
              <table width="540" border="0" align="center" cellpadding="10" cellspacing="0" class="tx_1">
                <tr>
                  <td align="left">
                    <p>138 Liverpool Rd, Ashfield 2131 <br/>
                      MAP: [ <a href="http://maps.google.com/maps?f=q&hl=en&q=WES+Components+138+Liverpool+Rd+Ashfield+sydney+australia&ie=UTF8&t=h&cd=1&sll=-33.890848,151.129818&sspn=0.008051,0.014591&ei=DhUlR6-GCZv2iwPJrbyuDw" target="_blank">
                        <span class="tx_3"><u>Google Maps</u></span></a> ]</p><p>
If heading from the City towards Liverpool<br/>
We are on the LEFT-HAND-SIDE</p>
                    <p>We are Next to the 7-Eleven Station<br/>
Car Parking Available.</p>
                    <!--<p>Office Opening Hours:<br/>-->
                    <p>
                      Monday to Friday<br/>
                      8:30am to 5.00pm Mon-Fri</p>
                    <p>
<!--Counter Opening Hours:<br/>-->
                      Saturday - Trade Counter Only<br/>
                      9:00am to 4.00pm Mon-Fri</p>
                    <p>
                      Public Holidays<br/>
                     
                      Closed
                    </p>
<!--9.00AM to 4:00PM Sat</p>-->
                    <p>Phone: (02) 9797 9866<br/>
FAX: (02) 9716 6015</p>
                    <p>
                      Email:  <a href="mailto:sales@wes.net.au" class="tx_3">
                        <span class="tx_3">
                          <u>sales@wes.net.au</u>
                        </span>
                      </a>
                  </p>
                  </td>
                </tr>
              </table>
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<br>