<table width="96%" border="0" cellpadding="0" cellspacing="0">

  <tr>
    <td>
      <table width="100%" border="0" cellspacing="0" cellpadding="5">
        <tr>
          <td align="left" class="tx_1">
            <a href="home.aspx"  style="color:#0099FF"  class="tx_3">Home</a><font style="font-family: Arial, Helvetica, sans-serif; font-weight:bolder; font-size: small; font-style: normal"> / </font>Contact Us
          </td>
        </tr>
        <tr>
          <td class="tx_3">
            <hr>
          </td>

        </tr>
      </table>
    </td>
  </tr>
  <tr>
    <td height="30" align="left" class="tx_7">CONTACT US</td>
  </tr>
  <tr>
    <td align="center" valign="top" class="tx_1">&nbsp;</td>
  </tr>
  <tr>
    <td align="center" valign="top" class="tx_1">
      <table width="558" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td height="30" background="images/17.gif">
            <table width="540" border="0" align="center" cellpadding="0" cellspacing="0">
              <tr>

                <td align="left" height="30" class="tx_6">INFORMATION</td>
                <td align="right">
                  <img src="images/ico_11.gif" width="14" height="17">
                </td>
              </tr>
            </table>
          </td>
        </tr>
        <tr>
          <td class="back_table_center1">
            <br>
              <table width="540" border="0" align="center" cellpadding="10" cellspacing="0" class="tx_1">
                <tr>
                  <td align="left">
                    <h1 style="font-size:16px;">Address</h1>
                    <p>
                      WES Australiasia<br />
                      84-90 Parramatta Road, <br />
                      Summer Hill, <br />
                      NSW 2130,
                      Australia
                      <br/>
                    </p>
                    
                      <h1 style="font-size:16px;">Business Hours</h1>
                    <p>Monday to Friday<br/>
8:30am to 5:00pm</p>
				
					  <p>Saturday - Trade Counter Only<br/>
						  <!--8:30 to 5.00 Mon-Fri, <br/>-->
						  9:00am to 4:00pm
					  </p>
					  <p>
						  Public Holidays<br/>
						  Closed
					  </p>
<!--9.00AM to 4:00PM Sat</p>-->
                      <h1 style="font-size:16px;">Phone</h1>
                    <p>Phone: (02) 9797 9866</p>
                      <h1 style="font-size:16px;">Fax</h1>
                      <p> FAX: (02) 9716 6015</p>
                      <h1 style="font-size:16px;">Email</h1>
                    <p>
                      Email:  <a href="mailto:sales@wes.net.au" class="tx_3">
                        <span class="tx_3">
                          <u>sales@wes.net.au</u>
                        </span>
                      </a>
                  </p>
                    <br />
                                       <div>
                            <div>
<div style="margin-bottom:20px">
                          <div>
  <h4 style="color: rgb(0, 0, 0); font-weight: bold; letter-spacing: 1px; font-size: 24px; margin-bottom:0px;">Directions to our store</h4>
  <span style="display: block;font-size: 15px;padding-bottom: 15px;padding-top: 8px;">Enter the address you are leaving from to get directions to our store</span>
</div>
     <div style="margin-bottom:10px;">
        <label class="tx_7" >Enter your Departing Address / Location</label>
                                
         </div>
                                  <div class="" style="width:100%;height:20px">
                                     
                                     <input type="text" style="width:100%; height:20px" class="input_dr" id="txtfromaddress" placeholder="Enter your address" /><br /><br />

                                    
                                   
                                             </div> 
    <div class="clear"></div>
    <div style="height:20px;text-align:right;margin-top:15px;">
         <button value="Submit" class="button normalsiz btngreen " style="height:29px;display:inline-block" type="button" onclick="embedmap('');">Find Route</button>
      <button value="Submit" class="button normalsiz btngreen " style="height:29px;display:inline-block" type="button" onclick="initialize_buttonclick('');">Route From Current Location</button>
  </div>
    <!--<div style="height:20px">
      
        </div>-->
                                
</div>
                              <div class="clear"></div>
                                <div  id="gmap" style="display:block;">
  <address>
     WES Australiasia, 84-90 Parramatta Road, Ashfield NSW 2130,Australia
  </address>
</div>
</div>
                            </div>

                  </td>
                </tr>
              </table>
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<br>