
<!--Comment by :palani
Comment on :20/07/2012-->

<!--<table align="left" width="100%" class="SearchResultsPaging">
  <tr>
    <td height="8"></td>
  </tr>
  <tr>
    <td>
      <table style=" solid #808080; width: 100%; font-family: tahoma; font-size: small;" id="CategoryTable">
        <tr>
          <td>
            <table width="100%" class="SearchResultsTable">
              <tr class="categoryheader">
                <td align="left"  valign="middle">
                  <b>Filter by Category test palani</b>
                </td>
                <td align="left" valign="middle">                  
                    <select id="category_filter1" style="width :245px" width="245px" name="category_filter1">
                      $TBWDataList:{
                      $it.TBWDataListItem$}$
                    </select>
                </td>
                <td align="left" valign="top">
                  <INPUT class="button-white" style="cursor:pointer;" type="button" value="Filter by Product Category test palani1" name="ApplyFilter" onclick="GetSelectedCat();" />
                </td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
    </td>
  </tr>
  <tr>
    <td height="10"></td>
  </tr>
</table>-->