<table width="180" border="0" cellspacing="0" cellpadding="0" >
  <tr>
    <td class="back_5">
      <table width="180" border="0" align="center" cellpadding="0" cellspacing="0">
        <tr>
          <td height="30" class="tx_6" align="center" style="background-color:#0157A7" width="50%" >
            <a  href="categorylist.aspx?ld=0&cid=$TBT_SELECTED_CATEGORY_ID$&byp=2" style ="color:White;text-decoration:none;" onclick="__doPostBack('','browsebybrand');">Browse By Product</a>
          </td>
        </tr>
      </table>
    </td>
  </tr>
  <tr>
    <td height="1">
    </td>
  </tr>
  <tr>
    <td>
      <div class="arrowlistmenu">
        <table width="180" border="0" cellpadding="0" cellspacing="0">
          <tr>
            <td align="LEFT" valign="bottom" width="180" >

              <ul>
              $TBT_SELECTED_CATEGORY_NAME$     