<td  align="left">
<a href="productdetails.aspx?&pid=$TBT_PRODUCT_ID$&fid=$TBT_FAMILY_ID$">$TBT_CODE$</a>
</td>
<td>
  $TBT_DESCRIPTION$
</td>
<td>
  &#36; $TBT_COST$
</td>
<td>
<a href="productdetails.aspx?&pid=$TBT_PRODUCT_ID$&fid=$TBT_FAMILY_ID$"  class="tx_3">
  <img src="images/ico_details.gif" width="17" height="14" border="0" align="absmiddle" /> Details
</a>
</td>
<td>
  <table>
    <tr>
      <td>
  <label>
    <input name="txt$TBT_PRODUCT_ID$_$TBT_QTY_AVAIL$_$TBT_MIN_ORD_QTY$_$TBT_FAMILY_ID$" type="text" size="5" id="txt$TBT_PRODUCT_ID$_$TBT_QTY_AVAIL$_$TBT_MIN_ORD_QTY$_$TBT_FAMILY_ID$" style="background-color:#FFFFFF;color: #000000;height=23px;" />
  </label>
      </td>
        <td><a onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image$TBT_PRODUCT_ID$_$TBT_FAMILY_ID$fp','','images/but_buy2.gif',1)">
      <img src="images/but_buy1.gif" name="Image$TBT_PRODUCT_ID$_$TBT_FAMILY_ID$fp" width="76" height="25" border="0" onClick="productbuy(txt$TBT_PRODUCT_ID$_$TBT_QTY_AVAIL$_$TBT_MIN_ORD_QTY$_$TBT_FAMILY_ID$,$TBT_PRODUCT_ID$);"/>
    </a>
      </td>
    </tr>
  </table>
</td>
