<table width="96%" border="0" cellpadding="0" cellspacing="0">
  <tr>
    <td>
      <table width="100%" border="0" cellspacing="0" cellpadding="5">
        <tr>
          <td align="left" class="tx_1">
            <a href="home.aspx"  style="color:#0099FF"  class="tx_3">Home</a>
            <font style="font-family: Arial, Helvetica, sans-serif; font-weight:bolder; font-size: small; font-style: normal"> / </font>$TBT_BREAD_CRUMBS$
          </td>
        </tr>
        <tr>
          <td class="tx_3">
            <hr/>
          </td>
        </tr>
      </table>
    </td>
  </tr>
  <tr>
    <td>
      <table>
        <tr>
          <td width="210" height="200">
            <a href="javascript:Zoom('prodimages$TBT_FWEB_IMAGE1$')" style="text-decoration:none;">
              <img src="prodimages$TBT_FTWEB_IMAGE1$" width="100px" height="100px" style="text-decoration:none; border:0;"/>
            </a>
          </td>

          <td  class="border_3"  valign="top" >
            <table>
              <tr>
                <td valign="top" width="346">
                  <p class ="tx_7">
                    $TBT_FAMILY_NAME$<hr/>
                    $TBT_DESCRIPTIONS$
                  </p>

                </td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
    </td>
  </tr>
  <tr>
    <td>
      <br/>
      <br/>
    </td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <%--~Family$TBT_FAMILY_ID$Product--%>
    <tr>
      <td>
        <table width="100%" cellspacing="2" cellpadding="2">
          <tr class="TableFHeadRow">
            <td>
              <strong>Item#</strong>
            </td>
            <td>
              <strong>Description</strong>
            </td>
            <td  >
              <strong>Cost</strong>
            </td>
            <td >
              <strong>More Info</strong>
            </td>
            <td >
              <strong>QTY</strong>
            </td>
          </tr>
          $TBWDataList:{
          $it.TBWDataListItem$}$
        </table>
      </td>
    </tr>
    <%--Family$TBT_FAMILY_ID$Product--%>
      <tr>
        <td align="center" valign="top" class="tx_1">
          <hr>
    </td>
      </tr>
    </table>
<p>
  <img src="images/img_creditcards.gif" width="405" height="117" vspace="20">
</p>


