<table width="100%">
  <tr>
    <td align="left" valign="top">
      <div  style="padding: 0 0 25px;width:325px;height:260px;">
        <div   id="product-image" class="gallery-view" style="height:210px;vertical-align: middle;" >
          <img style="display: block;max-height:256;max-width:256;" valign="top" align="left" src="prodimages$TBT_TFWEB_IMAGE1$"  alt=""/>
        </div>
        <div class="product-info">
          <div class="brand" style="padding: 10px 0 0 50px; margin:0; "></div>
          <div class="gallery-thumbnails" style="float: left;padding-bottom: 10px;padding-left: 10px;padding-right: 10px;padding-top: 10px;width: 290px;">
            <div id="gallery" style="margin-top:25px;float: left;padding: 10px;width: 290px;padding:0px;">
              <ul style="list-style: none outside none;padding: 1px;margin: 0px;width: auto;">
                $TBT_MULTIIMAGES:{
                <li width="60px" height="60px" style="background-attachment: scroll; background-clip: border-box;background-color: transparent; background-image: none; background-origin: padding-box; background-position: 0 0; background-repeat: repeat; background-size: auto auto; float: left; height: 60px; width: 60px;background: none repeat scroll 0 0 transparent;display: list-item;">
                  <img src="prodimages$it.Thumpnail$" alt=""  style="max-width:50px;max-height:50px;border: 2px solid #ccc;"/>
                </li>
                }$
              </ul>
            </div>
          </div>
        </div>
      </div>
    </td>
    <td valign="top">
      <div style="float: left; padding: 10;width: 450;margin-top:0px;">
        <h1 style="color: #666666;font-size: 14;text-align:left;font-family: Arial;">$TBT_FAMILY_NAME$</h1>

        
        <p style="font-size:11px;font-family: Arial;color: #666666;">
          $TBT_SHORT_DESCRIPTION$
        </p>
        <p style="text-align:left;font-size:13px;color: #666666;font-family: Arial;">
          $TBT_DESCALL$
        </p>
      
      </div>
    </td>
  </tr>
</table>
