<br/>
<table width="950px" border="0" cellpadding="0" cellspacing="0" style="margin:0 auto;margin-left:6px;" >
  <tr>
    <td align="left" >
      <table width="99%" style="border:solid 1px #E8E8E8;" cellpadding="0" cellspacing="0">
        <tr>
          <td height="2"></td>
        </tr>
        <tr>
          <td align='center' valign='middle'>
            <table width="100%" border="0" cellpadding="0" cellspacing="0">
              <tr>
                <td>
                  <table>
                    <tr>
                      <td width="100">
                          <img src="prodimages$TBT_FAMILY_TH_IMAGE$"  style="text-decoration:none; border:0;"/>
                      </td>
                      <td valign='middle' align='left'>
                        <p class ="tx_15" align='left' style='color:#1c629b;font-weight: bold;font-family: Arial,Tahoma,Helvetica;font-size: 12px;'>
                          $TBT_FAMILY_NAME$ 
                          <br/>
                        </p>
                        <p style='font-weight: normal;font-family: Arial,Tahoma,Helvetica;font-size: 11px;'>
                          $TBT_FAMILY_DESC$
                        </p>
                        <p>
                          $TBT_SHORT_DESCRIPTION$
                        </p>
                        <p>
                          $TBT_SHORT_DESCRIPTION1$
                        </p>
                        <p>
                          $TBT_SHORT_DESCRIPTION2$
                        </p>
                        <p>
                          $TBT_SHORT_DESCRIPTION3$
                        </p>
                        <p>
                          $TBT_SHORT_DESCRIPTION4$
                        </p>
                        <p>
                          $TBT_DESCRIPTIONS$
                        </p>

                      </td>
                    </tr>
                  </table>
                </td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>

