<table width="180" border="0" cellspacing="0" cellpadding="0" >
  <tr>
    <td class="back_5">
      <table width="160" border="0" align="center" cellpadding="0" cellspacing="0">
        <tr>
          <td height="30" class="tx_6" align="center">BROWSE CATEGORIES</td>
          <td>&nbsp;</td>
        </tr>
      </table>
    </td>
  </tr>
  <tr>
    <td height="1">     
    </td>
  </tr>  
  <tr>
    <td><div class="arrowlistmenu">
      <table width="180" border="0" cellpadding="0" cellspacing="0">
        <tr>
          <td align="LEFT" valign="bottom" width="180" >
            <ul>
              $TBT_SELECTED_CATEGORY_NAME$              
           