<!--Command by palani
Command on:20/07/2012-->


<!--<table width="180" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td class="back_7">
      <table width="160" border="0" align="center" cellpadding="0" cellspacing="0">
        <tr>
          <td height="30" class="tx_6" align="left">Filter by product details </td>
          <td>
          </td>
        </tr>
      </table>
    </td>
  </tr>
  <tr>
    <td align="center" class="border_1">
      <table width="180" border="0" cellpadding="5" cellspacing="0" class="tx_1">
        <tr>
          <td align="center">
            <TABLE>
              <TBODY>
                <TR>
                  <TD>
                    <TABLE style="WIDTH: 100%">
                      <TBODY>
                        <TR>
                          <TD style="WIDTH: 100px">&nbsp;</TD>
                          <TD style="WIDTH: 100px"></TD>
                          <TD vAlign="bottom"></TD>
                        </TR>
                        <TR>
                          <TD style="WIDTH: 100px">
                            <input class="button-white" type="submit" value="Apply Filters" name="ApplyFilter"   style ="cursor:pointer;" onclick="return GetSelectedItems();"/>
                            <br/>
                          </TD>
                          <TD style="WIDTH: 100px"></TD>
                          <TD vAlign="bottom"></TD>
                        </TR>
                      </TBODY>
                    </TABLE>
                    <div >
                      <TABLE class="bottom"
                      style="BORDER-COLLAPSE: collapse" cellSpacing="0" border="0">
                        <TBODY>
                          $TBWDataList:{
                          $it.TBWDataListItem$}$
                        </TBODY>
                      </TABLE>
                    </div>
                    <TABLE style="WIDTH: 100%">
                      <TBODY>
                        <TR>
                          <TD style="WIDTH: 100px">&nbsp;</TD>
                          <TD style="WIDTH: 100px"></TD>
                          <TD vAlign="bottom"></TD>
                        </TR>
                        <TR>
                          <TD style="WIDTH: 100px">
                            <input class="button-white" type="submit" value="Apply Filters"  style ="cursor:pointer;" name="ApplyFilter1" onclick="return GetSelectedItems();"/>
                          </TD>
                          <TD style="WIDTH: 100px"></TD>
                          <TD vAlign="bottom"></TD>
                        </TR>
                      </TBODY>
                    </TABLE>
                  </TD>
                </TR>
              </TBODY>
            </TABLE>
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>-->