//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DefaultTop {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DefaultTop() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DefaultTop", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item(s) in Cart.
        /// </summary>
        internal static string ItemsinCart {
            get {
                return ResourceManager.GetString("ItemsinCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        internal static string lbAccount {
            get {
                return ResourceManager.GetString("lbAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Search.
        /// </summary>
        internal static string lbAdvSearch {
            get {
                return ResourceManager.GetString("lbAdvSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company |.
        /// </summary>
        internal static string lbCompany {
            get {
                return ResourceManager.GetString("lbCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us .
        /// </summary>
        internal static string lbContacts {
            get {
                return ResourceManager.GetString("lbContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E Mail |.
        /// </summary>
        internal static string lbEmail {
            get {
                return ResourceManager.GetString("lbEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Out.
        /// </summary>
        internal static string lblCheckout {
            get {
                return ResourceManager.GetString("lblCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string lblHome {
            get {
                return ResourceManager.GetString("lblHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search :.
        /// </summary>
        internal static string lblSearch {
            get {
                return ResourceManager.GetString("lblSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Status.
        /// </summary>
        internal static string lborderstatus {
            get {
                return ResourceManager.GetString("lborderstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion |.
        /// </summary>
        internal static string lbPromotion {
            get {
                return ResourceManager.GetString("lbPromotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services |.
        /// </summary>
        internal static string lbService {
            get {
                return ResourceManager.GetString("lbService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping Cart.
        /// </summary>
        internal static string lbShoppingCart {
            get {
                return ResourceManager.GetString("lbShoppingCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier List |.
        /// </summary>
        internal static string lbSupplier {
            get {
                return ResourceManager.GetString("lbSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signout.
        /// </summary>
        internal static string lbtnSignOut {
            get {
                return ResourceManager.GetString("lbtnSignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Cart .
        /// </summary>
        internal static string lbViewCart {
            get {
                return ResourceManager.GetString("lbViewCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string lbWishlist {
            get {
                return ResourceManager.GetString("lbWishlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubTotal.
        /// </summary>
        internal static string subtotal {
            get {
                return ResourceManager.GetString("subtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string WelcomeNote {
            get {
                return ResourceManager.GetString("WelcomeNote", resourceCulture);
            }
        }
    }
}
