//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Invoice {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Invoice() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Invoice", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Address:.
        /// </summary>
        internal static string lblbAdd {
            get {
                return ResourceManager.GetString("lblbAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        internal static string lblBill {
            get {
                return ResourceManager.GetString("lblBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BILL TO :.
        /// </summary>
        internal static string lblBillAdd {
            get {
                return ResourceManager.GetString("lblBillAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout Steps :.
        /// </summary>
        internal static string lblCheck {
            get {
                return ResourceManager.GetString("lblCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string lblConfirm {
            get {
                return ResourceManager.GetString("lblConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name on Credit Card :.
        /// </summary>
        internal static string lblCreditName {
            get {
                return ResourceManager.GetString("lblCreditName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card Number :.
        /// </summary>
        internal static string lblCreditNumber {
            get {
                return ResourceManager.GetString("lblCreditNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Order .
        /// </summary>
        internal static string lblReviewOrder {
            get {
                return ResourceManager.GetString("lblReviewOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELIVERY TO : .
        /// </summary>
        internal static string lblSAdd {
            get {
                return ResourceManager.GetString("lblSAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping.
        /// </summary>
        internal static string lblShip {
            get {
                return ResourceManager.GetString("lblShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Method :.
        /// </summary>
        internal static string lblShipMethod {
            get {
                return ResourceManager.GetString("lblShipMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Provider : .
        /// </summary>
        internal static string lblShipProvider {
            get {
                return ResourceManager.GetString("lblShipProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping Cart.
        /// </summary>
        internal static string lblShoppingCart {
            get {
                return ResourceManager.GetString("lblShoppingCart", resourceCulture);
            }
        }
    }
}
