//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class login {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal login() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.login", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered invalid Password!.
        /// </summary>
        internal static string ErrorMsg01 {
            get {
                return ResourceManager.GetString("ErrorMsg01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is locked due to too many failed password attempts..
        /// </summary>
        internal static string ErrorMsg02 {
            get {
                return ResourceManager.GetString("ErrorMsg02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Account is Locked.Contact Adminintrator!.
        /// </summary>
        internal static string ErrorMsg021 {
            get {
                return ResourceManager.GetString("ErrorMsg021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered invalid User ID.
        /// </summary>
        internal static string ErrorMsg03 {
            get {
                return ResourceManager.GetString("ErrorMsg03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently your company is not active.Contact your company admin and then try again..
        /// </summary>
        internal static string ErrorMsg04 {
            get {
                return ResourceManager.GetString("ErrorMsg04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the password.
        /// </summary>
        internal static string ErrorMsg05 {
            get {
                return ResourceManager.GetString("ErrorMsg05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email address.
        /// </summary>
        internal static string ErrorMsg06 {
            get {
                return ResourceManager.GetString("ErrorMsg06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already logged in!.
        /// </summary>
        internal static string ErrorMsg07 {
            get {
                return ResourceManager.GetString("ErrorMsg07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Email ID is associated to multiple logins. Please login using your unique &quot;Login Name&quot;&quot;.
        /// </summary>
        internal static string ErrorMsg10 {
            get {
                return ResourceManager.GetString("ErrorMsg10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Account is not Active.Contact Administrator!.
        /// </summary>
        internal static string ErrorMsg11 {
            get {
                return ResourceManager.GetString("ErrorMsg11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email ID is associated to multiple logins.  Please login using your unique “Login Name” instead associated to your account.
        /// </summary>
        internal static string ErrorUuerMail {
            get {
                return ResourceManager.GetString("ErrorUuerMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Your Password ?.
        /// </summary>
        internal static string lbForgetPassWord {
            get {
                return ResourceManager.GetString("lbForgetPassWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to Register.
        /// </summary>
        internal static string lblClickHere {
            get {
                return ResourceManager.GetString("lblClickHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string lblHead {
            get {
                return ResourceManager.GetString("lblHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string LblStar {
            get {
                return ResourceManager.GetString("LblStar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        internal static string lblUserName {
            get {
                return ResourceManager.GetString("lblUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User ?.
        /// </summary>
        internal static string lbRegister {
            get {
                return ResourceManager.GetString("lbRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your registration is complete. Please Sign In to continue.
        /// </summary>
        internal static string lbRegSucess {
            get {
                return ResourceManager.GetString("lbRegSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset and sent to your email address. Check your email address and continue to login.
        /// </summary>
        internal static string msgForgotPassWord {
            get {
                return ResourceManager.GetString("msgForgotPassWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your User Id(s) sent to your email address. Check your email address and continue to login.
        /// </summary>
        internal static string msgForgotuserid {
            get {
                return ResourceManager.GetString("msgForgotuserid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset successfully. Continue to login with new password.
        /// </summary>
        internal static string msgResetPassword {
            get {
                return ResourceManager.GetString("msgResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset successfully. Continue to login with new password.
        /// </summary>
        internal static string RESETPASSWORD {
            get {
                return ResourceManager.GetString("RESETPASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Password.
        /// </summary>
        internal static string rfvPassWord {
            get {
                return ResourceManager.GetString("rfvPassWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter User ID.
        /// </summary>
        internal static string rfvUserName {
            get {
                return ResourceManager.GetString("rfvUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must Sign In to continue....
        /// </summary>
        internal static string Txtlog {
            get {
                return ResourceManager.GetString("Txtlog", resourceCulture);
            }
        }
    }
}
