<table width="170" border="0" cellpadding="4" cellspacing="0" class="tx_1">
  <tr>
    <td colspan="2" valign="top" align="left"  class="tx_7A">
      <a href="family.aspx?&fid=$TBT_FAMILY_ID$&cid=$TBT_CATEGORY_ID$&path=$FAMILY_EA_PATH$">$TBT_FAMILY_NAME$</a>
      <br/>
    </td>
  </tr>
  <tr>
    <td rowspan="2" valign="top" align="left">
      <strong>
        <a href="productdetails.aspx?&pid=$TBT_PRODUCT_ID$&fid=$TBT_FAMILY_ID$&cid=$TBT_CATEGORY_ID$&path=$PRODUCT_EA_PATH$">
          <img src="prodimages$TBT_TWEB_IMAGE1$" width="45" height="45" class="border"/>
          <!--<img data-original="prodimages$TBT_TWEB_IMAGE1$" width="45" height="45" style=" border: 3px solid #e8e8e8;margin: 0;padding: 2px;" class="lazy"/>-->
        </a>
        <br/>

      </strong>
    </td>
    <td  width="59%" height="30px" align="left">
      <a href="productdetails.aspx?&pid=$TBT_PRODUCT_ID$&fid=$TBT_FAMILY_ID$&cid=$TBT_CATEGORY_ID$&path=$PRODUCT_EA_PATH$">
        <strong>$TBT_CODE$</strong>
      </a>
    </td>
  </tr>
  <tr>
    <td colspan="2" align="left" valign="top">$TBT_DESCRIPTION1$</td>
  </tr>
  <tr>
    <td colspan="2" valign="top">
      <hr/>
    </td>
  </tr>
</table>