<table width="180" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td class="back_5" width="100%">
      <table width="180" border="0" align="left" cellpadding="0" cellspacing="0">
        <tr>
          <td height="30" class="tx_6" align="left">&nbsp;&nbsp;&nbsp;NEW PRODUCTS</td>
          <td align="left" width="27px">
            <img src="images/ico_11.gif" width="14" height="17"/>
            </td>
        </tr>
      </table>
    </td>
  </tr>
  <tr>
    <td align="center" valign="top">
      <table width="180" border="0" cellpadding="5" cellspacing="0" class="tx_1">
        <tr>
          <td align="right" valign="top" class="back_tb_cost">
            $TBWDataList:{
            $it.TBWDataListItem$}$
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>
