<div class="selectfirst active">
  <div class="productsearch pfclear">
    <div class="numbox1">
      1
    </div>
    <span class="darkgray opensans600">Selected Device Brand</span>
    <span class="clearfix">
      <h3>$SELECTED_BRAND$</h3>
    </span>
    <div class="select-wrap martop15">
      <select  onchange="location = this.options[this.selectedIndex].value;" class="filter-option hasCustomSelect" style="width: 168px; position: absolute; opacity: 0; height: 38px; font-size: 17px;">
        <option Value="" >&#60;select Brand&#62;</option>
        $BRAND_LI_LIST$
      </select>
      <span class="customSelect filter-option" style="display: inline-block;">
        <span class="customSelectInner" style="width: 152px; display: inline-block;">$SELECTED_BRAND$</span>
      </span>
    </div>
  </div>
  <div class="searched_image">
    <img src="$BRAND_IMAGE$" style="min-width:100px;height:40px">
                                    </div>
</div>
