
<div class="selectfirst-blue">
  <div class="numbox">
    1

  </div>
  <span class="opensans600">Select Brand Of Device</span>
  <div class="select-wrap">
    <select onchange="location = this.options[this.selectedIndex].value;" name="forma" class="filter-option hasCustomSelect" style="width: 168px; position: absolute; opacity: 0; height: 38px; font-size: 17px;">
      <option Value="" >&#60;$SELECTED_BRAND$&#62;</option>
      $BRAND_LI_LIST$
    </select>
    <span class="customSelect filter-option" style="display: inline-block;">
      <span class="customSelectInner" style="width: 152px; display: inline-block;">&#60;$SELECTED_BRAND$&#62;</span>
    </span>
  </div>
</div>

