<div class="selectfirst active">
  <div class="productsearch">
    <div class="numbox1">
      1
    </div>
    <span class="darkgray opensans600">First Cable Side</span>
    <span>
      <div style="width:225px;">
        <h3>$SELECTED_CABLE$</h3>
      </div>
    </span>
    <div>

    </div>
  </div>
  <div class="searched_image">
    <img src="$CABLE_IMAGE$" style="min-width:100px;height:40px;">
</div>
</div>