


   <div class="tabs_home">
        <ul class="tab-links_home">
            <li class="active"><a class="newpro_tb" href="#nproducts">New Products</a></li>
            <li><a class="clearance_tb" href="#clearance">Clearance</a></li>
            <li><a class="specials_tb" href="#specials">Specials</a></li>
        </ul>
        <div class="tab-content_home">
            <div id="nproducts" class="tab_home active">
                $TBWDataList:{
        $it.TBWDataListItem$}$
            <p></p>
            </div>
            <div id="clearance" class="tab_home">
              
             $TBWDataList_c:{
        $it.TBWDataListItem$}$
         
            </div>
            <div id="specials" class="tab_home">
             
              $TBWDataList_s:{
        $it.TBWDataListItem$}$
            <p></p>
            </div>
        </div>
	</div>
