<table style="display:none;">
<tr>
  <!--
  <td height="10"></td>
</tr>
</table>
<table width="558" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td height="30" background="images/23.gif">
      <table width="540" border="0" align="center" cellpadding="0" cellspacing="0">
        <tr>
          <td height="30" class="tx_1">
            <strong> PRODUCTS SEARCH</strong>
          </td>          
        </tr>
      </table>
    </td>
  </tr>
  <tr>
    <td height="126" align="center" class="back_9">
      <div style="width:588px; height:150px; overflow:auto; ">
        <table width="550" border="0" align="center" cellpadding="10" cellspacing="0" class="tx_1">
          <tr>
          -->
            $TBWDataList:{
            $it.TBWDataListItem$}$
            <!--
            <td width="115" valign="bottom">
              <input name="button2" type="button" class="form_boton" id="button2" value="Apply Filters"  onclick="GetSelectedItemsFilter();"/>
            </td>
          </tr>
        </table>
      </div>
    </td>
    -->
  </tr>
</table>

