<table width="96%" border="0" cellpadding="0" cellspacing="0">
  <tr>
    <td>
      <table width="100%" border="0" cellspacing="0" cellpadding="5">
        <tr>
          <td class="tx_1" align="left">
            <a href="home.aspx" class="tx_3" style="color:#0099FF">Home</a><font style="font-family: Arial, Helvetica, sans-serif; font-weight:bolder; font-size: small; font-style: normal"> / </font>Shipping Info
          </td>
        </tr>
        <tr>
          <td class="tx_3">
            <hr/>
          </td>
        </tr>
      </table>
    </td>
  </tr>
  <tr>
    <td height="30" class="tx_7" align="left">SHIPPING INFO</td>
  </tr>
  <tr>
    <td class="tx_1" align="left">Typical consumer orders to a residential physical address within the 48 contiguous states normally will be shipped via FedEx Ground within 1-2 business days of receipt of order. Orders for schools and businesses normally will be shipped via FedEx Ground within 4 business days of receipt. Orders will be delivered within 1-5 business days after shipping. Click here to see a map with expected FedEx Ground shipping times. </td>
  </tr>
  <tr>
    <td align="center" valign="top" class="tx_1">
      <br>
        <table width="540" border="0" align="center" cellpadding="0" cellspacing="0" class="tx_1">
          <tr>
            <td>&nbsp;</td>
            <td height="50" align="center">
              <img src="images/logo_fedex_c.gif" width="77" height="39"/>
            </td>
            <td align="center">
              <img src="images/logo_fedex_c.gif" width="77" height="39"/>
            </td>
            <td align="center">
              <img src="images/logo_fedex_c.gif" width="77" height="39"/>
            </td>
            <td align="center">
              <img src="images/logo_fedex_c.gif" width="77" height="39"/>
            </td>
          </tr>
          <tr>
            <td class="border_4"> up to 29.99</td>
            <td align="center" bgcolor="#F8F8F8" class="border_4"> 7.95</td>
            <td align="center" bgcolor="#F8F8F8" class="border_4"> 7.95</td>
            <td align="center" bgcolor="#F8F8F8" class="border_4"> 7.95</td>
            <td align="center" bgcolor="#F8F8F8" class="border_4"> 7.95</td>
          </tr>
          <tr>
            <td class="border_4">up to 29.99</td>
            <td align="center" class="border_4"> 7.95</td>
            <td align="center" class="border_4"> 7.95</td>
            <td align="center" class="border_4"> 7.95</td>
            <td align="center" class="border_4"> 7.95</td>
          </tr>
          <tr>
            <td class="border_4">up to 29.99</td>
            <td align="center" bgcolor="#F8F8F8" class="border_4"> 7.95</td>
            <td align="center" bgcolor="#F8F8F8" class="border_4"> 7.95</td>
            <td align="center" bgcolor="#F8F8F8" class="border_4"> 7.95</td>
            <td align="center" bgcolor="#F8F8F8" class="border_4"> 7.95</td>
          </tr>
          <tr>
            <td class="border_4">up to 29.99</td>
            <td align="center" class="border_4"> 7.95</td>
            <td align="center" class="border_4"> 7.95</td>
            <td align="center" class="border_4"> 7.95</td>
            <td align="center" class="border_4"> 7.95</td>
          </tr>
        </table>
        <br/>
    </td>
  </tr>
  <tr>
    <td align="center" valign="top" class="tx_1">
      <table width="558" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td height="30" background="images/17.gif">
            <table width="540" border="0" align="center" cellpadding="0" cellspacing="0">
              <tr>
                <td height="30" class="tx_6" align="left">INFORMATION</td>
                <td align="right">
                  <img src="images/ico_11.gif" width="14" height="17"/>
                </td>
              </tr>
            </table>
          </td>
        </tr>
        <tr>
          <td valign="top" class="back_table_center1">
            <br/>
            <table width="540" border="0" align="center" cellpadding="10" cellspacing="0" class="tx_1">
              <tr>
                <td width="188" valign="top">
                  <p align="center">
                    <img src="images/logo_fedex_g.gif" width="135" height="57"/>
                  </p>
                </td>
                <td width="312" valign="top" class="border_3" align="left">
                  <p>
                    Dick Blick ships all orders via FedEx ground whenever possible, except orders addressed to P.O. Boxes which will ship via USPS Parcel Post (FedEx ground charges will apply). Also, additional charges may apply on shipments of hazardous materials via air or to AK and HI. Call 1-800-447-8192 for information.<br>
</p>
                  <p>
                    Express Shipment &mdash; Express orders must be placed before 2:00 pm CST. Express shipments are expedited through our order process and generally ship via FedEx Overnight or 2-Day air, although other carriers are sometimes used. For items shipped directly from the factory (FOB), please add one additional day for processing. You will receive an order tracking number via email when your order is processed.<br>
                                Fedex Logo </p>
                  <p>
                    FedEx Ground &mdash; FedEx cannot deliver to a Post Office Box or to APO/FPO addresses. Allow 2 business days for order processing, plus 1&ndash;5 business days once merchandise leaves our warehouse. Orders placed on weekends or holidays will not be shipped until the following business day. FedEx orders can be tracked, while in transit; when your order ships, your confirmation e-mail will contain a tracking number and information. For expected shipping times via FedEx ground, see the map below.<br>
                              </p>
                  <p>USPS Parcel Post &mdash; Orders shipping to PO Boxes or APO/FPO addresses are shipped via USPS Parcel Post. Please allow 2 business days for order processing, plus 7&ndash;10 business days once merchandise leaves our warehouse. These orders cannot be tracked while in transit.</p>
                </td>
              </tr>
            </table>
            </td>
        </tr>
      </table>
      <br/>
      <br/>
      <br/>
      <br/>
      <br/>
      <br/>
    </td>
  </tr>
</table>










