<td class="tx_1A" align="center" height="150px" valign="center">
<table cellspacing="0" cellpadding="0" border="0">
  <tr>
<td width="100" valign="top">
 <a href="product_list.aspx?&ld=0&pcr=$TBT_PARENT_CATEGORY_ID$&amp;cid=$TBT_CATEGORY_ID$&amp;searchstr=$TBT_ATTRIBUTE_SEARCH$&amp;type=$TBT_ATTRIBUTE_TYPE$&amp;value=$TBT_ATTRIBUTE_VALUE$&amp;bname=$TBT_ATTRIBUTE_BRAND$&amp;byp=$TBT_CUSTOM_NUM_FIELD3$&amp;Path=$EA_PATH$"  class="tx_1A">
    <img src="prodimages$TBT_IMAGE_FILE$" width="100" height="100" border="0"/>
  </a>
 </td> 
 </tr>
 <tr>
   <td>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="product_list.aspx?&ld=0&pcr=$TBT_PARENT_CATEGORY_ID$&amp;cid=$TBT_CATEGORY_ID$&amp;searchstr=$TBT_ATTRIBUTE_SEARCH$&amp;type=$TBT_ATTRIBUTE_TYPE$&amp;value=$TBT_ATTRIBUTE_VALUE$&amp;bname=$TBT_ATTRIBUTE_BRAND$&amp;byp=$TBT_CUSTOM_NUM_FIELD3$&amp;Path=$EA_PATH$"  class="tx_1A">$TBT_CATEGORY_NAME$</a><br/>
   </td>
 </tr>
 </table>
</td>