      <div class="box_main"   >
        <div class="box1"  style="width:769px;height:108px">
          <!--<img src="prodimages$TBT_IMAGE_FILE$" alt="" class="push_left imgstyle1"/>-->

          <img data-original="prodimages$TBT_IMAGE_FILE$" alt="" class="lazy" style="float: left;background: none repeat scroll 0 0 #ffffff;border: 1px solid #e0e0e0;border-radius: 4px;margin: 0 10px 0 0;padding: 3px;"/>
          <div style="width:500px; float:left">
            <h6 style="font-size: 12px;text-align: left;">$TBT_CATEGORY_NAME$</h6>
            <p class="p2 push_left" >$TBT_SHORT_DESC$ </p>
          </div>
          <div class="push_right"  style="width:120px;margin:20px 0 0 0 ">
            $if(TBT_PDF_STATUS)$
            <p class="p2 push_left" >
              <!--<a href="attachments$PDF$" target="_blank" class="downpdf"></a>-->
              <a href="$PDF$" target="_blank" class="downpdf"></a>
              $PDF1$
            </p>
            $endif$
            <p class="p2 push_left"  >
            <a href="$TBT_EBOOK_LINK$" target="_blank" class="viewpdf" style="display:$TBT_DISPALY_EBOOK_LINK$;"></a >
          </p>
            $if(TBT_WESNEWS_LINK)$
            <p class="p2 push_left"  >              
              <a href="CatalogueDownload.aspx?ActionResult=NEWS" target="_blank" class="downpdf" ></a>
            </p>
            $endif$
          </div>
          <div class="clear"></div>

        </div >
       
      </div >
       <div  style="height:10px;width:100%;margin-top:124px;">
       
       </div>






