<table align="center" width="100%" border="0" cellpadding="0" cellspacing="0" class="border_1">
  <tr>
    <td valign="bottom">
      <table width="100%" border="0" cellpadding="0" cellspacing="0" class="tx_1">
        <tr height="35">
          <td>
            <table width="100%" border="0" cellpadding="0" cellspacing="0" class="tx_1">
              <tr>
                <TD height="39" vAlign="top" width="11">
                  <IMG alt="" src="Images/Fr_Cr_5.png" width="11" height="39">
              </TD>

                <TD style="BACKGROUND-IMAGE: url(Images/Fr_center_1.png); BACKGROUND-REPEAT: repeat-x" class="txt_14" height="39" width="550" align="left">
                  <IMG hspace="10" alt="" src="Images/downarrow_G.png" width="24" height="12"> $TBW_CATEGORY_NAME$ 
              </TD>
                <TD style="BACKGROUND-IMAGE: url(Images/Fr_center_1.png); BACKGROUND-REPEAT: repeat-x" class="txt_14" height="39" width="170" align="left">

                </TD>
                <TD height="39" vAlign="top" width="10">
                  <IMG alt="" src="Images/Fr_Cr_6.png" width="10" height="39" />
                </TD>
              </tr>
            </td>
        </tr>
      </table>
    </td>
  </tr>
  <tr style="display:$TBT_DISPLAY_LINK$;">
    <td>
      <table width="100%" bgColor="#f2f2f2" border="0" cellSpacing="0" cellPadding="0">
        <tr>

          <TD align="left" >
            <div class="listingmenu" style="display:$TBT_DISPLAY_LINK$;">
              <p class="p2 push_left" >
                <a href="$TBT_EBOOK_LINK$" target="_blank" style="color:Blue;float:left;display:$TBT_DISPLAY_EBOOK_LINK$;"></a>
              </p>
                <!--<a href="attachments$PDF$" class="downpdf" target="_blank" style="margin-left:3px;" ></a>-->
              <p class="p2 push_left" >
                <a href="$PDF$" class="downpdf" target="_blank" style="margin-left:3px;" ></a>
              </p>
                </div>
          </TD>
        </tr>
      </table>
    </td>
  </tr>
  <tr>
    <td align="center">
      <iframe src="$TBT_ADV_URL_LINK$" border="0" frameborder="0" width="760" height="1000px" ></iframe>
    </td>
  </tr>
</table>
