  <a href="product_list.aspx?&amp;id=0&amp;pcr=$TBW_PARENT_CATEGORY_ID$&amp;cid=$TBW_CATEGORY_ID$&amp;tsb=$TBW_BRAND$&amp;tsm=$TBW_MODEL$&amp;searchstr=$TBW_ATTRIBUTE_SEARCH$&amp;type=$TBW_ATTRIBUTE_TYPE$&amp;value=$TBW_ATTRIBUTE_VALUE$&amp;bname=$TBW_ATTRIBUTE_BRAND$&amp;byp=$TBW_CUSTOM_NUM_FIELD3$&amp;Path=$EA_PATH$"  style="width:118px; height:170px; display:block;  float:left; margin-right:8px;">
        <div style="width:115px; height:115px; margin:auto auto; position:relative; border:1px solid #ccc;">
        <img style="padding:2%; max-width:98%; position:absolute; top: 50%;left: 50%; transform: translate(-50%,-50%); margin:auto;" src="prodimages$TBT_IMAGE_FILE$"/>
        </div>
        <h4 style="padding:0; margin:0; color:#0071cf; font-size:12px; text-align:center; margin-top:10px; margin-bottom:10px;">$SUB_CAT_NAME$</h4>
       
    </a>