<td class="tx_1A" height="160px" valign="center" align="left" style="border-left:none 0px Black; border-bottom:dashed 1px Black; border-top:dashed 0px Black; border-right:dashed 1px Black; ">
<table cellspacing="0" cellpadding="0" border="0" width="150px">
  <tr>
<td width="100" valign="top" align="center">
  
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <a href="categorylist.aspx?&id=0&cid=$TBT_CAT_ID$&tsb=$TBT_TOSUITE_BRAND$&byp=2&bypcat=1" class="tx_1A">
    <img src="prodimages$TBT_IMAGE_FILE$" style="max-height:100px; max-width:100px;" border="0"/>
  </a>
 </td> 
 </tr>
 <tr>
   <td align="center">
     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="categorylist.aspx?&id=0&cid=$TBT_CAT_ID$&tsb=$TBT_TOSUITE_BRAND$&byp=2&bypcat=1" class="tx_1A"><b>$TBT_TOSUITE_BRAND1$</b></a><br/>
   </td>
 </tr>
 </table>
</td>