<td class="tx_1A" height="160px" valign="center" align="center" >
<table cellspacing="0" cellpadding="0" border="0" width="150px">
  <tr>
    <td height="154" align="center" width="150" valign="bottom" style="background-image: url('Images/model_top.png'); background-repeat: no-repeat;">    
  <a href="bybrand.aspx?&id=0&cid=$TBT_CAT_ID$&tsb=$TBT_TOSUITE_BRAND$&tsm=$TBT_TOSUITE_MODEL$&amp;Path=$EA_PATH$&amp;byp=2" class="tx_1A">
    <!--<img src="prodimages$TBT_IMAGE_FILE$" style="max-height:100px; max-width:100px;" border="0"/>-->
    <img data-original="prodimages$TBT_IMAGE_FILE$" style="max-height:100px; max-width:100px;" border="0" class="lazy" alt=""/>
  </a>
 </td> 
 </tr>
 <tr>
   <td height="29" align="center" width="150px" style="background-image: url('Images/model_middle.png'); background-repeat: repeat-y;">          
     <a href="bybrand.aspx?&amp;id=0&amp;cid=$TBT_CAT_ID$&amp;tsb=$TBT_TOSUITE_BRAND$&amp;tsm=$TBT_TOSUITE_MODEL$&amp;Path=$EA_PATH$&amp;byp=2" class="tx_1A"><b>$TBT_TOSUITE_MODEL1$</b></a><br/>    
   </td>
 </tr>
  <tr>
    <td height="6" valign="top" style="background-image: url('Images/model_bottom.png'); background-repeat: no-repeat;">
    </td>
  </tr>
 </table>
</td>