<td align="center" valign="top" class="border_1">
  <table width="150" border="0" cellspacing="0" cellpadding="4">
    <tr>
      <td align="left">
        <br/>
        <strong class="tx_1">$TBT_PARENT_CATEGORY_NAME$</strong>
      </td>
    </tr>
    <tr>
      <td align="left">
        <br/>
        $TBT_SUB_CATEGORY_LIST$
      </td>
    </tr>
    <tr>
      <td height="10">       
        
      </td>
    </tr>
  </table>
</td>






