<table width="96%" border="0" cellpadding="0" cellspacing="0">
  <tr>
    <td>
      <table width="100%" border="0" cellspacing="0" cellpadding="5">
        <tr>
          <td class="tx_1" align="left">
            <a href="home.aspx" class="tx_3" style="color:#0099FF">Home</a><font style="font-family: Arial, Helvetica, sans-serif; font-weight:bolder; font-size: small; font-style: normal"> / </font>Site Map
          </td>
        </tr>
        <tr>
          <td class="tx_3">
            <hr>
          </td>
        </tr>
      </table>
    </td>
  </tr>
  <tr>
    <td height="30" class="tx_7" align="left">SITE MAP</td>
  </tr>
  <tr>
    <td class="tx_1" align="left">If you can't find the information you need, please use the Make an Enquiry page or phone 1300 13 900 and get help from a Customer Service representative. </td>
  </tr>
  <tr>
    <td align="center" valign="top" class="tx_1">&nbsp;</td>
  </tr>
  <tr>
    <td align="center" valign="top" class="tx_1">
      <table width="558" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td height="30" background="images/17.gif" align="left">
            <table width="540" border="0" align="center" cellpadding="0" cellspacing="0">
              <tr>
                <td height="30" class="tx_6">STRUCTURE</td>
                <td align="right">
                  <img src="images/ico_11.gif" width="14" height="17">
                </td>
              </tr>
            </table>
          </td>
        </tr>
        <tr>
          <td align="center" valign="top" class="back_table_center1">
            <table width="100%" border="0" cellspacing="0" cellpadding="5">
              <tr>
                
                  $TBWDataList:{
                  $it.TBWDataListItem$}$
                
              </tr>
              <tr>
                <td colspan="3" align="center" valign="top"  background="images/17.gif" class="border_1">
                  <table width="540" border="0" align="center" cellpadding="0" cellspacing="0">
                    <tr>
                      <td height="20" class="tx_6" align="left">CUSTOMER SERVICE</td>
                      <td align="right">
                        <img src="images/ico_11.gif" width="14" height="17"/>
                      </td>
                    </tr>
                  </table>
                </td>
              </tr>
              <tr>
                <td align="center" valign="top">
                  <table width="150" border="0" cellpadding="4" cellspacing="0" class="tx_1">
                    <tr>
                      <td class="tx_1" align="left">
                        <br/>
                        <strong>My Account</strong>                       
                      </td>
                    </tr>
                    <tr>
                      <td valign="top" align="left">
                        <br/>
                        <a href="EditUserProfile.aspx" class="tx_4">View Profile</a><br/>
                        <a href="changePassword.aspx" class="tx_4">Change Password</a>
                        <br/>
                        <a href="Orders.aspx?ViewType=HISTORY" class="tx_4">Order History</a>
                       </td>
                    </tr>
                  </table>
                  </td>
                <td align="center" valign="top">
                  <table width="150" border="0" cellpadding="4" cellspacing="0" class="tx_1">
                    <tr>
                      <td class="tx_1" align="left">
                        <br/>
                        <strong>Company Info</strong>
                      </td>
                    </tr>
                    <tr>
                      <td align="left">
                        <br/>
                        <a href="aboutus.aspx" class="tx_4">About Us</a>
                        <br/>
                        <a href="contactus.aspx" class="tx_4">Contact Us</a>
                        <br/>
                        <a href="#" class="tx_4">Terms and Conditions</a>
                        <br/>
                        <a href="privacepolicy.aspx" class="tx_4">Privacy Policy</a>
                        <br/>
                        <a href="CatalogueDownload.aspx" class="tx_4">Catalogue Download</a>
                        <br/>
                        <a href="Newsupdate.aspx" class="tx_4">News Letter Download</a>
                        <br/>
                        <!--<a href="http://www.wes.com.au/info/" class="tx_4">WES Electronic News</a>
                        <br/>-->
                      </td>
                    </tr>
                  </table>
                </td>
              </tr>
            </table>
            <br/>
          </td>
        </tr>
      </table>
      <br/>
      <br/>
      <br/>
      <br/>
      <br/>
      <br/>
    </td>
  </tr>
</table>

