<td height="175" valign="top" class="border_2">
          <table width="175" border="0" cellpadding="2" cellspacing="0">
            <tr>
              <td height="30" colspan="2" valign="top" align="left"  class="tx_7">
                <a href="productdetails.aspx?&pid=$TBT_PRODUCT_ID$&fid=$TBT_FAMILY_ID$">$TBT_FAMILY_NAME$</a>
              </td>
            </tr>

            <tr>
              <td height="50" colspan="2" valign="top" align="left" class="tx_1">$TBT_DESCRIPTIONS1$</td>
            </tr>
            <tr>
              <td width="101" align="left" valign="top">
                <table width="80" border="0" cellspacing="0" cellpadding="0">
                  <tr>
                    <td height="30" valign="top">
                      <span class="tx_7B">
                        <a href="productdetails.aspx?&pid=$TBT_PRODUCT_ID$&fid=$TBT_FAMILY_ID$">$TBT_CODE$</a>
                      </span>
                      <br/>
                      <span class="tx_9">&#36;&nbsp;$TBT_COST$</span>
                    </td>
                  </tr>

                  <tr>
                    <td>
                      <br/>
                      <a href="OrderDetails.aspx?&bulkorder=1&Pid=$TBT_PRODUCT_ID$&Qty=$TBT_MIN_ORD_QTY$&ORDER_ID=$TBT_ORDER_ID$" onMouseOut="MM_swapImgRestore()" onMouseOver="MM_swapImage('Image$TBT_PRODUCT_ID$_p','','images/but_buy2.gif',1)">
                       
                          <img src="images/but_buy1.gif" name="Image$TBT_PRODUCT_ID$_p" width="76px" height="25px" border="0"/>
                       
                      </a>
                    </td>
                  </tr>
                </table>
              </td>
              <td width="74" align="right" valign="top">
                <a href="productdetails.aspx?&pid=$TBT_PRODUCT_ID$&fid=$TBT_FAMILY_ID$">
                  <div style="display:table-cell; vertical-align:middle; width:65px;height:100%;"  align="center">
                  <img src="prodimages$TBT_TWEB_IMAGE1$" name="" height="100%"  width="65px" class="border"/>
                  </div>
                </a>
                </td>
            </tr>
          </table>
</td>
        