<table width="370" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td class="back_7" ALIGN="LEFT">
      <div class="padding">&nbsp;&nbsp;&nbsp;PRODUCT HIGH LIGHTS</div>
    </td>
  </tr>
  <tr>
    <td align="center" class="border_1">
      <table width="350" border="0" cellpadding="5" cellspacing="0">

        $TBWDataList:{
        $it.TBWDataListItem$}$
      </table>
    </td>
  </tr>
</table>
