<td class="tx_1A" align="center" height="150px" valign="center">
<table cellspacing="0" cellpadding="0" border="0">
  <tr>
<td width="100" valign="top">
  <a href="product_list.aspx?&cid=$TBT_CATEGORY_ID$&&byp=2" class="tx_1A">
    <img src="prodimages$TBT_IMAGE_FILE$" width="100" height="100" border="0"/>
  </a>
 </td> 
 </tr>
 <tr>
   <td>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="product_list.aspx?&cid=$TBT_CATEGORY_ID$&&byp=2" class="tx_1A"><b>$TBT_CATEGORY_NAME$</b></a><br/>
   </td>
 </tr>
 </table>
</td>