<table width="575px" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td height="10px"></td>
  </tr>
  <tr>
    <td>
  <table width="100%" border="0" cellspacing="0" cellpadding="0">
    <tr>
      <td width="90" valign="top">
        <img src="prodimages$TBT_IMAGE_FILE$" width="100" height="100" border="0"/>
      </td>
      <td width="10px"></td>
      <td valign="top" align="left"  class="SearchResultsPaging2">
        <p class="tx_7A">
          <img src="images/Plus symbol.jpg"/> $TBT_CATEGORY_NAME$
        </p>
        <p>$TBT_SHORT_DESC$</p>
      </td>
    </tr>
  </table>
</td>
</tr>
<tr>
<td height="10px"></td>
</tr>
<tr>
<td>
  <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td align="left" valign="top"  width="30%" >
            <table width="100%" border="1" cellspacing="0" cellpadding="0">
              $TBWDataList:{
              $it.TBWDataListItem$}$
            </table>
          </td>
          <td align="left" valign="top" width="30%">
           <table width="100%" border="1" cellspacing="0" cellpadding="0">
              $TBWDataList1:{
              $it.TBWDataListItem$}$
            </table>
          </td>
          <td align="left" valign="top" width="30%">
            <table width="100%" border="1" cellspacing="0" cellpadding="0"> 
              $TBWDataList2:{
              $it.TBWDataListItem$}$
            </table>
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>

