<div class="drop_products">  <img src="prodimages$TBT_PRODUCT_TH_IMAGE$" width="80" height="80" alt="img" />
<a href="/productdetails.aspx?pid=$TBT_PRODUCT_ID$&fid=$TBT_FAMILY_ID$&cid=$TBT_CATEGORY_ID$&path=$PRODUCT_EA_PATH$"><strong>$TBT_FAMILY_NAME$</strong></a>
<p>$FAMILY_DESC$ $if(TBT_SHOW_MORE)$ ...<a href="/productdetails.aspx?pid=$TBT_PRODUCT_ID$&fid=$TBT_FAMILY_ID$&cid=$TBT_CATEGORY_ID$&Path=$PRODUCT_EA_PATH$" style="color:#0099FF;text-decoration:none;">More Information</a>$endif$
</p><div style="Color:red">Code :<strong>$PRODUCT_CODE$</strong> &nbsp;&nbsp;&nbsp;&nbsp;Price :<strong style="red">&#36 $PRODUCT_PRICE$</strong>
</div><div class="clear"></div></div>