<td align="left" valign="center" >
  <!--<a href="bybrand.aspx?&pgno=$TBW_PAGE_NO$&cid=$TBW_CATEGORY_ID$&sl1=$TBT_SUBCATID_L1$&sl2=$TBT_SUBCATID_L2$&tsb=$TBT_TOSUITE_BRAND$&tsm=$TBT_TOSUITE_MODEL$&byp=2" class="tx_10A">$TBW_PAGE_NO$</a> -</td>-->
<a href="bybrand.aspx?pgno=$TBW_PAGE_NO$&cid=$TBW_CATEGORY_ID$&tsb=$TBT_TOSUITE_BRAND$&tsm=$TBT_TOSUITE_MODEL$&amp;searchstr=$TBW_ATTRIBUTE_SEARCH$&type=$TBW_ATTRIBUTE_TYPE$&amp;value=$TBW_ATTRIBUTE_VALUE$&amp;bname=$TBW_ATTRIBUTE_BRAND$&amp;byp=$TBW_CUSTOM_NUM_FIELD3$&amp;Path=$EA_PATH$"  class="tx_10A">$TBW_PAGE_NO$</a> -</td>

