<!--<td align="center" valign="top" >-->
  <div  style="float:left;padding:5px;">
    <table width="312" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td height="200" valign="top" class="back_8">
          <table width="312" border="0" cellspacing="0" cellpadding="0">
            <tr>
              <td height="30" align="center">
                <div class="padding2">$TBT_PARENT_CATEGORY_NAME$</div>
              </td>
            </tr>
            <tr>
              <td height="165" align="center" valign="top">
                <table width="300" border="0" cellpadding="5" cellspacing="0">
                  <tr valign="top">
                    <td width="107" height="170" valign="middle" align="left">
                      $TBT_SUB_CATEGORY_LIST$
                    </td>
                    <td width="173" rowspan="2">
                      <table width="170" border="0" cellspacing="0" cellpadding="4">
                        <tr>
                          <td width="90" valign="top">
                            <a href="categorylist.aspx?&ld=0&cid=$TBT_PARENT_CATEGORY_ID$&byp=$TBT_CUSTOM_NUM_FIELD3$&path=$EA_PATH$" style="text-decoration:none;">
                              <!--<img src="prodimages$TBT_PARENT_CATEGORY_IMAGE$" width="100" height="100" border="0"/>-->
                              <img data-original="prodimages$TBT_PARENT_CATEGORY_IMAGE$"  border="0" class="lazy"/>
                            </a>
                          </td>
                          <td width="64" valign="top">
                            <span class="tx_8"></span>
                          </td>
                        </tr>
                        <tr>
                          <td colspan="2" valign="top" align="left" class="tx_1">
                            <a href="categorylist.aspx?&ld=0&cid=$TBT_PARENT_CATEGORY_ID$&byp=$TBT_CUSTOM_NUM_FIELD3$&path=$EA_PATH$"  class="tx_1_link">$TBT_SHORT_DESC$</a>
                          </td>
                        </tr>
                      </table>
                    </td>
                  </tr>
                  <tr>
                    <td valign="bottom" align="left">
                      <a href="categorylist.aspx?&ld=0&cid=$TBT_PARENT_CATEGORY_ID$&byp=$TBT_CUSTOM_NUM_FIELD3$&path=$EA_PATH$" class="tx_3" style="cursor:pointer;">
                        <strong>Click here </strong>
                        <br/>to See Full List
                      </a>
                    </td>
                  </tr>
                </table>
              </td>
            </tr>
          </table>
        </td>
      </tr>
      <tr>
        <td valign="top" class="back_8_bottom" height="7">
        </td>
      </tr>
    </table>
  </div>
<!--</td>-->


