<table align="center" width="558" style="display:none">

<tr>
  <td height="30" class="tx_7">$TBW_CATEGORY_NAME$</td>
</tr>
<tr>
  <td align="center" valign="top">
    <table width="100%" border="0" cellpadding="4" cellspacing="0" class="tx_1">
      <!--
      <tr>
        <td>
          <img src="images/ico_12.gif" width="21" height="21" border="0" align="absmiddle"> Refine your search by selecting from the criteria below. 
        </td>
      </tr>
      -->
     <!-- <tr>
        <td>
          <hr/>
        </td>
      </tr>-->
        
      <!--<tr>
        <td>
          <br /><strong>Product Category:</strong><br>
            $TBWDataList:{
            $it.TBWDataListItem$}$
        </td>

      </tr>-->
    </table>
  </td>
</tr>
  <!--<tr>
    <td height="10"></td>
  </tr>-->
</table>

        
                      
                                   
                         
              

