<div>
  $TBT_SPLCORRECTION$
</div>
<div class="box2" style="width:761px;">
  <div class="searchpagesearch"  >
    <input type="text" id="txtSearch" Class="topsearch1" placeholder="Search WES! Enter Keywords or Part No's" value="$TBT_TXTSEARCH$" ></input>
    <input type="Button" ID="btnSearch" runat="server" Class="hoverbtn searchbtn" style="border:0px;cursor:pointer;"  OnClick="return searchurl();"></input>
  </div>

</div>

<br/>
<div align="center" class="tx_13">No Products were found that match your selection.</div>


