<td align="left" valign="center" >
  $if(TBW_VIEWTYPE1)$
  <a href="powersearch.aspx?&pgno=$TBW_PAGE_NO$&cid=$TBW_CATEGORY_ID$&amp;searchstr=$TBW_ATTRIBUTE_SEARCH$&amp;type=$TBW_ATTRIBUTE_TYPE$&amp;value=$TBW_ATTRIBUTE_VALUE$&amp;bname=$TBW_ATTRIBUTE_BRAND$&amp;byp=$TBW_CUSTOM_NUM_FIELD3$&amp;Path=$EA_PATH$&amp;ViewMode=LV" class="tx_10A">$TBW_PAGE_NO$</a> $TBW_PAGE_Minus$
  $else$
  <a href="powersearch.aspx?&pgno=$TBW_PAGE_NO$&cid=$TBW_CATEGORY_ID$&amp;searchstr=$TBW_ATTRIBUTE_SEARCH$&amp;type=$TBW_ATTRIBUTE_TYPE$&amp;value=$TBW_ATTRIBUTE_VALUE$&amp;bname=$TBW_ATTRIBUTE_BRAND$&amp;byp=$TBW_CUSTOM_NUM_FIELD3$&amp;Path=$EA_PATH$&amp;ViewMode=GV" class="tx_10A">$TBW_PAGE_NO$</a> $TBW_PAGE_Minus$
  $endif$
</td>
  




