<div>
  <table width="100%">
    <tr>
      $if(TBT_DES_SHOW)$
      <td width='150' >
        <img id='img1'  height="91" width="101" src='/images/WesLogo.jpg'></img>
      </td>
      <td width='75px'>
        
      </td>
      <td width='250'>
        <span style="font-weight:bold;font-family: Arial;font-size: 16;"> WES AUSTRALASIA</span>
        <p align='left' class='TitleColumnStyleOrdRpt' style='margin-top:1px;font-size:14px;color: #666666;font-family: Arial;'>

          <!--<span style="font-weight:bold;"> WES AUSTRALASIA  </span>
          <br />-->
          Web: www.wes.net.au
          <br />
          Email: sales@wes.net.au

        </p>

      </td>
      <td width='250'>
        <p align='left' class='TitleColumnStyleOrdRpt' style='font-size:14px;color: #666666;font-family: Arial;'>
          Phone: +61 2 9797 9866
          <br />
          Fax: +61 2 9798 0017

        </p>
      </td>
      <td width='310'>
        <p  align='left' class='TitleColumnStyleOrdRpt' style='font-size:14px;color: #666666;font-family: Arial;'>
          Address: 138 Liverpool Road,
          <br />
          Ashfield, NSW, 2131, Australia

        </p>
      </td>
      $endif$
    </tr>
  
  </table>
  <br/>
  <table>

    <tr>
      <td width='700'>
        <div style="font-size:11px; color:#1b5d9b;font-family: Arial;">
          $lblbreadcrum$<img alt='' style='vertical-align:middle; margin-left:5px;margin-top:-2px;' height='12px' width='14px' src= 'images/close11.png' />
        </div>
      </td>
    </tr>
  </table>
  
</div>





