<table width="180" border="0" cellpadding="0" cellspacing="0">  
  <tr>
    <td width="180" height="30" valign="top">
      <div class="title6" style="font-weight:normal;text-align:left;">Quick Find by Brand & Model</div>
    </td>
  </tr>
  <tr>
    <td height="92" valign="top">
      <table width="100%" border="0" cellpadding="0" cellspacing="0" class="search_bdr">       
        <tr>
          <td width="10" height="15" colspan=""></td>
          <td width="158"></td>
          <td width="12"></td>
        </tr>
        $TBWDataList:{
        $it.TBWDataListItem$}$        
      </table>
    </td>
  </tr>
  <tr>
    <td height="10" valign="top">
    </td>
  </tr>
</table>