<table>
  <tr><td>$Product$</td></tr>
  <tr><td>$moreproducts$</td></tr>
  <tr><td>$login$</td></tr>
  <tr><td>$aboutus$</td></tr>
  <tr><td>$contactus$</td></tr>
  <tr><td>$cataloguerequest$</td></tr>
  <tr><td>$faq$</td></tr>
  <tr><td>$privacepolicy$</td></tr>
  <tr><td>$returns$</td></tr>
  <tr><td>$Shipping_Info$</td></tr>
  <tr><td>$SSL_Security_Seal$</td></tr>
  <tr><td>$sitemap$</td></tr>
  <tr><td>$family$</td></tr>
  <tr><td>$BulkOrder$</td></tr>
  <tr><td>$Termsandconditions$</td></tr>

  
</table>