<table style="border: 0.5px solid #808080; width: 100%; font-family: tahoma; font-size: small;" id="CategoryTable">
  <tr>
    <td>
      <table  class="SearchResultsTable" style="width: 100%">
        <tr class="categoryheader">
          <td colspan="3">
            <strong>Filter by Category</strong>
            <INPUT class="button-white" type="submit" value="Apply Filters" name="ApplyFilter" onclick="GetSelItems('chkcat');"/>
          </td>
        </tr>
        $TBWDataList:{
        $it.TBWDataListItem$}$
        <tr class="categoryheader">
          <td colspan="3">
            <strong>Filter by Category</strong>
            <INPUT class="button-white" type="submit" value="Apply Filters" name="ApplyFilter" onclick="GetSelItems('chkcat');"/>
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>

