<table width="96%" border="0" cellpadding="0" cellspacing="0">
  <tr>
    <td>
      <table width="100%" border="0" cellspacing="0" cellpadding="5">
        <tr>
          <td class="tx_1" align="left">
            <a href="home.aspx" class="tx_3" style="color:#0099FF">Home</a><font style="font-family: Arial, Helvetica, sans-serif; font-weight:bolder; font-size: small; font-style: normal"> / </font>FAQ&acute;s
          </td>
        </tr>
        <tr>
          <td class="tx_3">
            <hr/>
          </td>
        </tr>
      </table>
    </td>
  </tr>
<tr>
  <td height="30" class="tx_7" align="left">FAQ&acute;S</td>
</tr>
<tr>
  <td class="tx_1" align="left">Find out more about WES. If you can't find the information you need, please use the Make an Enquiry page or phone 1100 13 933 and get help from a Customer Service representative.</td>
</tr>
<tr>
  <td align="center" valign="top">&nbsp;</td>
</tr>
<tr>
  <td align="center" valign="top">
    <table width="558" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td height="30" background="images/17.gif">
          <table width="540" border="0" align="center" cellpadding="0" cellspacing="0">
            <tr>
              <td height="30" class="tx_6" align="left">INFORMATION</td>
              <td align="right">
                <img src="images/ico_11.gif" width="14" height="17">
              </td>
            </tr>
          </table>
        </td>
      </tr>
      <tr>
        <td class="back_table_center1">
          <table width="540" border="0" align="center" cellpadding="10" cellspacing="0" class="tx_1">
            <tr>
              <td width="231" valign="top" align="left">
                <p>
                  <strong>Your Account </strong>
                </p>
                <p>
                  - How to create an account<br/>
                    - How to edit account information<br/>
                                forgot my password</p>
                <p>
                  <strong>Ordering Information </strong>
                </p>
                <p>
                  - How to get complete order history and tracking<br/>
                    - How to generate a price quote<br/>
                      - How to cancel your order<br/>
                        - When will my back order arrive?<br/>
                          - APO / FPO Orders<br/>
                            - How to re-order<br/>
                              - Product Availability<br/>
                                - Sales Tax</p>
                <p>
                  <strong>Shipping Information</strong>
                </p>
                <p>
                  - Order Tracking<br>
                    - Order History &amp; Tracking<br/>
                      - Shipping Options &amp; Costs<br/>
                        - Cannot Ship UPS Items<br/>
                          - Free Shipping<br/>
                                - Next Day Delivery</p>
                <p>
                  <strong>Shoplet Info </strong>
                </p>
                <p>
                  - Low Prices<br/>
                    - Why shop with us?<br/>
                      - Protecting your credit card<br/>
                        - Customer Testimonials<br/>
                                - About us</p>
              </td>
              <td width="269" valign="top" class="border_3" align="left">
                <p>
                  <strong>What is our return policy? </strong>
                </p>
                <p>
                  - Exchanges<br/>
                    - What is our policy regarding defective products?<br/>
                                - Technical Support</p>
                <p>
                  <strong>Payment Information </strong>
                </p>
                <p>
                  - Methods of payment we accept<br/>
                    - How to obtain a copy of your receipt<br/>
                      - Do we accept purchase orders?<br/>
                        - Do we offer corporate accounts?<br/>
                          - Government and Education Accounts<br/>
                                - Sales Tax</p>
                <p>
                  <strong>Shop with Confidence </strong>
                </p>
                <p>
                  - Free Exchange - Easy Returns<br/>
                    - Safe &amp; Secured Shopping Guaranteed<br/>
                                - Privacy Policy</p>
                <p>
                  <strong>Privacy and International Order Information</strong>
                  <br>
                    <br>
                      - What is our privacy policy?<br/>
                        - Our policies on International purchases<br/>
                          - Protecting your credit card<br/>
                            - Disclaimer<br/>
                              - Copyright<br/>
                              </p>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
    <br/>
      <br/>
        <br/>
          <br/>
            <br/>
              <br/>
  </td>
</tr>
</table>



















